// =============================================================================
// REAL RESEARCH DATA — Al Moayyed Contracting Group & Nordic Group
// =============================================================================

export interface CompanyProfile {
  id: string;
  name: string;
  websiteUrl: string;
  aiSummary: string;
  primarySector: string;
  secondarySectors: string[];
  country: string;
  city: string;
  sizeCategory: string;
  employeeRange: string;
  yearsInOperation: number;
  ownershipType: string;
  capabilities: string[];
  productsServices: string[];
  certifications: string[];
  keyProjects?: string[];
  leadership?: { name: string; role: string }[];
  geographicPresence?: string[];
  financialInfo?: {
    estimatedRevenue?: string;
    revenueSource?: string;
    contractorGrade?: string;
    majorContracts?: { project: string; value: string; client: string }[];
    marketPosition?: string;
    marketShare?: string;
    industryBenchmarks?: { metric: string; value: string }[];
    bankingRelationships?: string[];
    awards?: string[];
    parentCompany?: string;
    subsidiaries?: string[];
    totalGroupEmployees?: string;
    forbesRanking?: string;
  };
  confidenceScores: Record<string, number>;
}

export interface Opportunity {
  id: string;
  title: string;
  type: "grant" | "financing" | "tender" | "rfp" | "training" | "incentive";
  sourceName: string;
  sourceCountry: string;
  sourceUrl?: string;
  description: string;
  sectors: string[];
  deadline: string;
  valueMax: string;
  status: "open" | "upcoming" | "closing_soon";
}

export interface Match {
  id: string;
  companyId: string;
  opportunityId: string;
  opportunityTitle: string;
  opportunityType: string;
  sourceName: string;
  sourceCountry: string;
  combinedScore: number;
  eligibilityScore: number;
  relevanceScore: number;
  competitivenessScore: number;
  recommendation: string;
  summary: string;
  keyFactors: string[];
}

// =============================================================================
// COMPANY PROFILES
// =============================================================================

export const companies: Record<string, CompanyProfile> = {
  nordic: {
    id: "nordic",
    name: "Nordic Group",
    websiteUrl: "nordicbh.com",
    aiSummary:
      "Nordic Group is an independent mid-scale luxury hospitality operator in Bahrain managing three properties totaling ~176 accommodation units. They specialize in family-friendly resort experiences targeting GCC leisure travelers, with secondary strength in wellness/spa and business meeting facilities.",
    primarySector: "Hospitality & Tourism",
    secondarySectors: ["Wellness/Spa", "Food & Beverage"],
    country: "BH",
    city: "Manama",
    sizeCategory: "sme",
    employeeRange: "51-200",
    yearsInOperation: 10,
    ownershipType: "independent",
    capabilities: [
      "Luxury villa accommodation management",
      "Spa and wellness services",
      "Event and meeting facility management",
      "Family tourism packages",
      "F&B operations (restaurant, cafe)",
      "Multi-property hospitality operations",
    ],
    productsServices: [
      "Nordic Resort (44 family villas)",
      "Nordic Palace & Spa (84 rooms/suites)",
      "Nordic Gardens (48 bungalow villas)",
    ],
    certifications: [],
    confidenceScores: {
      sector: 0.95,
      size: 0.7,
      capabilities: 0.85,
      years: 0.6,
      geography: 0.9,
    },
  },

  almoayyed: {
    id: "almoayyed",
    name: "Al Moayyed Contracting Group",
    websiteUrl: "almoayyedcg.com",
    aiSummary:
      "Al Moayyed Contracting Group (ACG) is one of Bahrain's largest AA-grade contractors, part of the Y.K. Almoayyed & Sons conglomerate (Forbes #51 Top Arab Family Businesses). Operating since 1971 with 6,500+ employees, ACG delivers end-to-end construction services including civil works, MEP, interiors, facility management, landscaping, cleaning, security, and real estate development. The group has completed landmark projects including Bahrain International Airport, the F1 Racing Circuit, and the 47-storey Almoayyed Tower.",
    primarySector: "Construction & Contracting",
    secondarySectors: [
      "Facility Management",
      "Real Estate Development",
      "MEP Engineering",
      "Cleaning & Environmental Services",
      "Security Services",
      "Transportation & Logistics",
      "Landscaping",
      "Scaffolding & Access Solutions",
    ],
    country: "BH",
    city: "Manama",
    sizeCategory: "large",
    employeeRange: "6,500+",
    yearsInOperation: 54,
    ownershipType: "family-conglomerate",
    capabilities: [
      "AA-Grade Civil & Building Construction",
      "Electromechanical (MEP) Engineering",
      "Interior Design & Fit-Out",
      "Scaffolding & Formwork Systems",
      "Integrated Facility Management",
      "Industrial & Commercial Cleaning",
      "Landscaping & Irrigation",
      "Manned Security & Surveillance",
      "Fleet Management & Transportation",
      "Real Estate Development & Investment",
      "Data Center Construction",
      "Power Plant & IWPP Construction",
      "Solar PV Installation (via Almoayyed Solar)",
      "Ready-Mix Concrete Production (via NCC)",
      "Precast Concrete Manufacturing",
    ],
    productsServices: [
      "Civil & Building Construction (high-rise, residential, commercial, industrial)",
      "Electromechanical Engineering (HVAC, electrical, plumbing, fire fighting)",
      "Interior Fit-Out & Finishing Works",
      "Scaffolding & Temporary Works",
      "Facility Management (hard & soft services)",
      "Cleaning Services (industrial, commercial, residential)",
      "Landscaping & Grounds Maintenance",
      "Security Services (guarding, CCTV, access control)",
      "Transportation & Fleet Services",
      "Real Estate Development (Almoayyed Tower, The Garnet)",
    ],
    certifications: [
      "ISO 9001:2015 (Quality Management)",
      "ISO 14001:2015 (Environmental Management)",
      "BS OHSAS 18001:2007 (Health & Safety)",
      "AA Grade — Bahrain Ministry of Works (highest classification)",
    ],
    keyProjects: [
      "Harbour Row, Bahrain Financial Harbour (~$150M, 450 residential units)",
      "AMAS Island Housing (~$166.8M, 682 apartments — JV with Airolink)",
      "Almoayyed Tower, Seef (BD 20M, 47-storey commercial tower)",
      "East Sitra Housing Project (546 social villas)",
      "Bahrain International Airport — New Passenger Terminal",
      "Formula 1 Racing Circuit, Bahrain",
      "Gulf International Convention Centre",
      "Gulf International Bank Headquarters",
      "Batelco White Space Data Center (first solar-powered in Bahrain)",
      "Al Dur II IWPP (10% equity stake — power & water project)",
    ],
    leadership: [
      { name: "Mohammed Farouk Almoayyed", role: "Chairman (since March 2025)" },
      { name: "Fareed Yousuf Almoayyed", role: "Deputy Chairman" },
      { name: "Mona Yousuf Almoayyed", role: "Managing Director" },
    ],
    geographicPresence: ["Bahrain", "GCC Region"],
    financialInfo: {
      estimatedRevenue: "~$576.5 million (2025 est.)",
      revenueSource: "Dun & Bradstreet / ZoomInfo estimates — privately held, unaudited",
      contractorGrade: "AA — Bahrain Ministry of Works (highest classification)",
      majorContracts: [
        { project: "Harbour Row, Bahrain Financial Harbour", value: "~$150M", client: "GFH Real Estate" },
        { project: "AMAS Island Housing (Islands 10 & 11)", value: "~$166.8M", client: "Ministry of Housing, Bahrain" },
        { project: "Almoayyed Tower, Seef", value: "~$53M (BD 20M)", client: "Almoayyed Properties" },
        { project: "East Sitra Housing Project", value: "Undisclosed", client: "Ministry of Housing" },
        { project: "Batelco White Space Data Center", value: "Undisclosed", client: "Batelco / Beyon Group" },
      ],
      marketPosition: "Top 3-5 contractor in Bahrain. Estimated larger than publicly listed Nass Corporation (~$401M revenue).",
      marketShare: "~10-12% of Bahrain's $3.2B construction market (construction-specific revenue est. $300-400M)",
      industryBenchmarks: [
        { metric: "Bahrain Construction Market Size (2025)", value: "$3.17-3.4 billion" },
        { metric: "Market CAGR (2025-2031)", value: "4.13%" },
        { metric: "Projected Market Size (2031)", value: "$4.04 billion" },
        { metric: "Residential Share", value: "~45%" },
        { metric: "Commercial Share", value: "~30%" },
        { metric: "Infrastructure Pipeline", value: "$30 billion multi-year" },
      ],
      bankingRelationships: [
        "National Bank of Bahrain (NBB) — Chairman was Farouk Y. Almoayyed (2011-2024)",
        "Bahrain National Holding (BNH) — Farouk Almoayyed serves as Chairman",
        "BMMI BSC — Mohammed Almoayyed is Director (since 2004)",
        "National Finance House — Mohammed Almoayyed is Vice Chairman (since 2006)",
      ],
      awards: [
        "Forbes #51 Top 100 Arab Family Businesses (2024) — #1 in Bahrain",
        "100 Million Employee Hours Without Lost Time Injury (April 2024)",
        "Ministry of Works: Recommended for any high-specification project",
        "Bahrain's First Solar-Powered White Space Data Center (2024)",
      ],
      parentCompany: "Y.K. Almoayyed & Sons BSC (c) — Founded 1940",
      subsidiaries: [
        "Almoayyed Properties (real estate)",
        "National Concrete Company — NCC (ready-mix, precast)",
        "Almoayyed International Group (ICT, solar, engineering, F&B)",
        "Almoayyed Motors (Ford, Lincoln)",
        "Almoayyed Air Conditioning",
        "Almoayyed Express Lift Co.",
        "Ashrafs W.L.L.",
      ],
      totalGroupEmployees: "13,000+ across all group entities",
      forbesRanking: "#51 Top 100 Arab Family Businesses — #1 in Bahrain",
    },
    confidenceScores: {
      sector: 0.98,
      size: 0.95,
      capabilities: 0.97,
      years: 0.99,
      geography: 0.95,
      financial: 0.75,
    },
  },
};

// =============================================================================
// OPPORTUNITIES — REAL DATA FROM MIDDLE EAST RESEARCH
// =============================================================================

export const opportunities: Opportunity[] = [
  // --- BAHRAIN ---
  {
    id: "bh-tamkeen-enterprise",
    title: "Tamkeen Enterprise Support Program",
    type: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/programs/",
    description: "Grants covering up to 50% of eligible costs including software, services, hardware, marketing, and branding within an approved cap. Designed for growing Bahraini businesses.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Up to 50% of costs",
    status: "open",
  },
  {
    id: "bh-tamkeen-nep",
    title: "National Employment Program 3.0",
    type: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/programs/national-employment-program-3-0/",
    description: "Wage subsidies for Bahraini job seekers and fresh graduates for up to 36 months. Incentivizes private sector hiring of Bahrainis in priority sectors.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Wage subsidy up to 36 months",
    status: "open",
  },
  {
    id: "bh-tamkeen-training",
    title: "Professional Training & Certification",
    type: "training",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/",
    description: "Funds professional certifications and skills development for Bahraini employees including technical, management, and leadership training programs.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Varies by program",
    status: "open",
  },
  {
    id: "bh-tamkeen-export",
    title: "Export / Overseas Expansion Program",
    type: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/",
    description: "Financial assistance for businesses looking to expand into international markets. Supports market entry, exhibitions, and business development abroad.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Varies",
    status: "open",
  },
  {
    id: "bh-tamkeen-digital",
    title: "Digital Transformation Support",
    type: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/",
    description: "Support for digital transformation initiatives across Bahraini businesses. Over 8,400 institutions assisted to date.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Varies",
    status: "open",
  },
  {
    id: "bh-bdb-sme",
    title: "BDB SME Fund ($185M)",
    type: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    sourceUrl: "https://www.bdb-bh.com/",
    description: "Sharia-compliant financing with flexible repayment up to 5 years. Tamkeen subsidizes profit rates by up to 50%. Covers fixed assets and working capital for 7 strategic sectors.",
    sectors: ["Tourism", "Manufacturing", "Logistics", "IT", "Finance", "Health", "Education"],
    deadline: "Open (since Nov 2025)",
    valueMax: "Up to $185M fund",
    status: "open",
  },
  {
    id: "bh-bdb-finance",
    title: "BDB & Tamkeen Joint Finance",
    type: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    sourceUrl: "https://www.bdb-bh.com/",
    description: "Partnership financing with subsidized profit rates for SMEs. Covers business term loans, working capital, and growth financing.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  {
    id: "bh-bdb-invoice",
    title: "BDB Invoice Discounting (Tijara)",
    type: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    sourceUrl: "https://www.tijara.bh/",
    description: "Supply chain financing allowing SMEs to receive early payment on invoices from registered buyers. Recently launched with Alba as anchor buyer.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Based on invoices",
    status: "open",
  },
  {
    id: "bh-export-finance",
    title: "Export Bahrain Financing",
    type: "financing",
    sourceName: "Export Bahrain",
    sourceCountry: "BH",
    sourceUrl: "https://export.bh/",
    description: "Export financing up to BD 1 million with profit rate subsidies up to 70%. Includes export credit insurance, market intelligence, and trade facilitation.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "BD 1,000,000 (~$2.65M)",
    status: "open",
  },
  {
    id: "bh-tender-board",
    title: "Bahrain Tender Board — Government Procurement",
    type: "tender",
    sourceName: "Bahrain Tender Board",
    sourceCountry: "BH",
    sourceUrl: "https://etendering.tenderboard.gov.bh/",
    description: "All civilian government tenders above BD 10,000. Annual procurement volume ~BHD 3.2 billion. Registered vendors can bid on construction, infrastructure, and service contracts.",
    sectors: ["Construction", "Infrastructure", "Services", "IT"],
    deadline: "Ongoing — per tender",
    valueMax: "BHD 3.2B annual volume",
    status: "open",
  },
  {
    id: "bh-edb-investment",
    title: "EDB Investment Facilitation",
    type: "incentive",
    sourceName: "Bahrain Economic Development Board",
    sourceCountry: "BH",
    sourceUrl: "https://www.bahrainedb.com/",
    description: "Free facilitation service for investors: registration support, incentive packages (0% corporate tax, 100% foreign ownership, BIIP/BLZ free zone benefits), and operational setup.",
    sectors: ["Financial Services", "Manufacturing", "ICT", "Tourism", "Logistics"],
    deadline: "Always Open",
    valueMax: "Tax & duty incentives",
    status: "open",
  },
  {
    id: "bh-biip-incentives",
    title: "Bahrain International Investment Park (BIIP)",
    type: "incentive",
    sourceName: "BIIP / EDB",
    sourceCountry: "BH",
    sourceUrl: "https://www.bahrainedb.com/bahrain-international-investment-park",
    description: "0% import duty on raw materials & equipment, competitive lease rates, 100% foreign ownership, duty-free GCC/GAFTA access, 15% electricity discount for manufacturing.",
    sectors: ["Manufacturing", "Logistics", "Services"],
    deadline: "Always Open",
    valueMax: "Ongoing incentives",
    status: "open",
  },
  // --- SAUDI ARABIA ---
  {
    id: "sa-nidlp",
    title: "National Industrial Development & Logistics Program (NIDLP)",
    type: "incentive",
    sourceName: "Saudi Ministry of Industry",
    sourceCountry: "SA",
    sourceUrl: "https://www.vision2030.gov.sa/",
    description: "Part of Vision 2030, providing incentives, licensing facilitation, and investment support for industrial and logistics companies entering the Saudi market.",
    sectors: ["Construction", "Manufacturing", "Logistics", "Mining"],
    deadline: "Ongoing",
    valueMax: "Project-dependent",
    status: "open",
  },
  {
    id: "sa-sidf",
    title: "Saudi Industrial Development Fund (SIDF)",
    type: "financing",
    sourceName: "SIDF",
    sourceCountry: "SA",
    sourceUrl: "https://www.sidf.gov.sa/",
    description: "Long-term, low-cost financing for industrial, energy, mining, and logistics projects. Finances up to 75% of project cost with repayment up to 20 years.",
    sectors: ["Construction Materials", "Manufacturing", "Energy", "Mining"],
    deadline: "Open",
    valueMax: "Up to 75% of project cost",
    status: "open",
  },
  {
    id: "sa-monshaat",
    title: "Monsha'at SME Support Programs",
    type: "grant",
    sourceName: "Monsha'at (General Authority for SMEs)",
    sourceCountry: "SA",
    sourceUrl: "https://www.monshaat.gov.sa/",
    description: "Comprehensive SME support including financing access, advisory services, government procurement access, and contractor qualification support.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Varies by program",
    status: "open",
  },
  {
    id: "sa-etimad",
    title: "ETIMAD — Saudi Government eProcurement",
    type: "tender",
    sourceName: "Ministry of Finance",
    sourceCountry: "SA",
    sourceUrl: "https://portal.etimad.sa/",
    description: "Unified Saudi government procurement portal. All ministry and government entity tenders published here. Massive construction pipeline under Vision 2030.",
    sectors: ["Construction", "Infrastructure", "IT", "Services"],
    deadline: "Ongoing — per tender",
    valueMax: "Billions SAR annually",
    status: "open",
  },
  {
    id: "sa-rcrc-neom",
    title: "NEOM — The Line & Related Projects",
    type: "tender",
    sourceName: "NEOM Company / PIF",
    sourceCountry: "SA",
    sourceUrl: "https://www.neom.com/",
    description: "$500B+ mega-project. Construction contracts for The Line, Trojena, Oxagon, Sindalah. MEP, civil, and specialist subcontracting packages available.",
    sectors: ["Construction", "MEP", "Infrastructure"],
    deadline: "Ongoing phases",
    valueMax: "$500B+ total project",
    status: "open",
  },
  {
    id: "sa-red-sea",
    title: "The Red Sea Project & AMAALA",
    type: "tender",
    sourceName: "Red Sea Global / PIF",
    sourceCountry: "SA",
    sourceUrl: "https://www.redseaglobal.com/",
    description: "Luxury tourism development with hotels, airports, and infrastructure. Construction packages for buildings, MEP, landscaping, and facility management.",
    sectors: ["Construction", "Hospitality", "MEP", "Landscaping"],
    deadline: "Ongoing phases",
    valueMax: "$10B+ combined",
    status: "open",
  },
  {
    id: "sa-diriyah",
    title: "Diriyah Gate Development",
    type: "tender",
    sourceName: "Diriyah Gate Development Authority",
    sourceCountry: "SA",
    sourceUrl: "https://www.dgda.gov.sa/",
    description: "$63B development on the outskirts of Riyadh. Cultural, hospitality, retail, and residential construction packages.",
    sectors: ["Construction", "Heritage", "Hospitality"],
    deadline: "Ongoing phases",
    valueMax: "$63B total",
    status: "open",
  },
  {
    id: "sa-roshn",
    title: "ROSHN Housing Developments",
    type: "tender",
    sourceName: "ROSHN / PIF",
    sourceCountry: "SA",
    sourceUrl: "https://www.roshn.sa/",
    description: "PIF-backed residential community developer. Multiple mega-communities across Saudi Arabia. Construction and FM packages for residential units and community infrastructure.",
    sectors: ["Construction", "Residential", "Facility Management"],
    deadline: "Ongoing",
    valueMax: "Multi-billion SAR",
    status: "open",
  },
  // --- UAE ---
  {
    id: "ae-khalifa-fund",
    title: "Khalifa Fund for Enterprise Development",
    type: "financing",
    sourceName: "Khalifa Fund",
    sourceCountry: "AE",
    sourceUrl: "https://www.khalifafund.gov.ae/",
    description: "SME financial support and training for businesses operating in or expanding to Abu Dhabi. Provides loans, equity, and advisory services.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies by program",
    status: "open",
  },
  {
    id: "ae-adgpg",
    title: "Abu Dhabi Government Procurement Gate",
    type: "tender",
    sourceName: "Abu Dhabi Government",
    sourceCountry: "AE",
    sourceUrl: "https://www.adgpg.gov.ae/",
    description: "Centralized procurement portal for Abu Dhabi government entities. Construction, infrastructure, and service contracts across all emirates.",
    sectors: ["Construction", "Infrastructure", "Services"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "ae-dubai-esupply",
    title: "Dubai eSupply Portal",
    type: "tender",
    sourceName: "Dubai Government",
    sourceCountry: "AE",
    sourceUrl: "https://esupply.dubai.gov.ae/",
    description: "Dubai government procurement portal. Tenders for construction, FM, cleaning, landscaping, and infrastructure maintenance.",
    sectors: ["Construction", "Facility Management", "Services"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "ae-etihad-rail",
    title: "Etihad Rail — National Railway",
    type: "tender",
    sourceName: "Etihad Rail",
    sourceCountry: "AE",
    sourceUrl: "https://www.etihadrail.ae/",
    description: "1,200km national railway network. Construction packages for stations, depots, civil works, and MEP across all emirates.",
    sectors: ["Construction", "Infrastructure", "MEP"],
    deadline: "Phase-dependent",
    valueMax: "$11B total project",
    status: "open",
  },
  // --- KUWAIT ---
  {
    id: "kw-nfund",
    title: "Kuwait National Fund for SME Development",
    type: "financing",
    sourceName: "National Fund for SME Development",
    sourceCountry: "KW",
    sourceUrl: "https://www.nationalfund.gov.kw/",
    description: "Financial support, training, and consulting for SMEs. Includes Mubader Plus workshops for entrepreneurs expanding in Kuwait.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  {
    id: "kw-capt",
    title: "Kuwait Central Agency for Public Tenders (CAPT)",
    type: "tender",
    sourceName: "CAPT",
    sourceCountry: "KW",
    sourceUrl: "https://capt.gov.kw/en/",
    description: "All Kuwaiti government tenders above 75,000 KD (~$248,500). Major infrastructure projects including Silk City, Kuwait Metro, and Al Mutlaa City.",
    sectors: ["Construction", "Infrastructure", "Services"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  // --- QATAR ---
  {
    id: "qa-monaqasat",
    title: "Qatar Monaqasat (Government eTendering)",
    type: "tender",
    sourceName: "Qatar Ministry of Finance",
    sourceCountry: "QA",
    sourceUrl: "https://monaqasat.mof.gov.qa/",
    description: "All Qatari government ministry tenders. Post-World Cup infrastructure and Qatar National Vision 2030 projects in construction and services.",
    sectors: ["Construction", "Infrastructure", "Services"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "qa-qdb",
    title: "Qatar Development Bank Programs",
    type: "financing",
    sourceName: "Qatar Development Bank",
    sourceCountry: "QA",
    sourceUrl: "https://www.qdb.qa/",
    description: "SME financing, advisory services, and market access support. Includes Al Dhameen credit guarantee scheme and Tasdeer export support.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  // --- OMAN ---
  {
    id: "om-tender-board",
    title: "Oman Tender Board — Government Procurement",
    type: "tender",
    sourceName: "Oman Tender Board",
    sourceCountry: "OM",
    sourceUrl: "https://etendering.tenderboard.gov.om/",
    description: "Government tenders across all sectors. Major projects in Duqm Special Economic Zone, Oman Rail, and tourism developments.",
    sectors: ["Construction", "Infrastructure", "Oil & Gas"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "om-riyada",
    title: "Riyada (Public Authority for SME Development)",
    type: "financing",
    sourceName: "Riyada",
    sourceCountry: "OM",
    sourceUrl: "https://www.riyada.om/",
    description: "SME support including financing, incubation, and business advisory. Al Raffd Fund provides microfinance and SME loans.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  // --- MULTILATERAL ---
  {
    id: "ml-isdb",
    title: "Islamic Development Bank (IsDB) — Project Finance",
    type: "financing",
    sourceName: "Islamic Development Bank",
    sourceCountry: "International",
    sourceUrl: "https://www.isdb.org/",
    description: "Sharia-compliant project financing, trade finance, and technical assistance for member countries. Infrastructure and construction are priority sectors.",
    sectors: ["Infrastructure", "Construction", "Energy", "Water"],
    deadline: "Project-based",
    valueMax: "Multi-billion USD portfolio",
    status: "open",
  },
  {
    id: "ml-afesd",
    title: "Arab Fund for Economic & Social Development (AFESD)",
    type: "financing",
    sourceName: "AFESD",
    sourceCountry: "International",
    sourceUrl: "https://www.arabfund.org/",
    description: "Concessional loans for infrastructure, energy, and industrial development projects across Arab countries. Active in construction and industrial sectors.",
    sectors: ["Infrastructure", "Construction", "Energy", "Industry"],
    deadline: "Project-based",
    valueMax: "Multi-million KD per project",
    status: "open",
  },
  {
    id: "ml-kfaed",
    title: "Kuwait Fund for Arab Economic Development (KFAED)",
    type: "financing",
    sourceName: "KFAED",
    sourceCountry: "KW",
    sourceUrl: "https://www.kuwait-fund.org/",
    description: "Development loans for infrastructure, transport, energy, and construction projects in developing countries. Procurement open to international contractors.",
    sectors: ["Infrastructure", "Construction", "Transport", "Energy"],
    deadline: "Project-based",
    valueMax: "Per project allocation",
    status: "open",
  },
  {
    id: "ml-adfd",
    title: "Abu Dhabi Fund for Development (ADFD)",
    type: "financing",
    sourceName: "ADFD",
    sourceCountry: "AE",
    sourceUrl: "https://www.adfd.ae/",
    description: "Development finance for infrastructure projects globally. Provides concessional loans, grants, and equity investments with construction procurement opportunities.",
    sectors: ["Infrastructure", "Construction", "Energy", "Housing"],
    deadline: "Project-based",
    valueMax: "AED 3B+ annual commitments",
    status: "open",
  },
  {
    id: "ml-sfd",
    title: "Saudi Fund for Development (SFD)",
    type: "financing",
    sourceName: "SFD",
    sourceCountry: "SA",
    sourceUrl: "https://www.sfd.gov.sa/",
    description: "Development loans for global projects with procurement opportunities for construction and infrastructure contractors.",
    sectors: ["Infrastructure", "Construction", "Energy"],
    deadline: "Project-based",
    valueMax: "Per project",
    status: "open",
  },
  // --- OIL & GAS PROCUREMENT ---
  {
    id: "og-bapco",
    title: "BAPCO Energies — Procurement",
    type: "tender",
    sourceName: "BAPCO Energies",
    sourceCountry: "BH",
    sourceUrl: "https://www.bapco.net/",
    description: "Bahrain's national oil company procurement. Construction, maintenance, and facility management contracts for refineries and production facilities.",
    sectors: ["Oil & Gas", "Construction", "Facility Management"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "og-aramco",
    title: "Saudi Aramco — iSupplier Portal",
    type: "tender",
    sourceName: "Saudi Aramco",
    sourceCountry: "SA",
    sourceUrl: "https://www.saudiaramco.com/",
    description: "World's largest oil company. Massive construction, MEP, and FM contracts. Contractor pre-qualification (IKTVA) for local and international companies.",
    sectors: ["Oil & Gas", "Construction", "MEP", "Facility Management"],
    deadline: "Ongoing",
    valueMax: "Multi-billion USD annually",
    status: "open",
  },
  {
    id: "og-adnoc",
    title: "ADNOC — Procurement & Supplier Portal",
    type: "tender",
    sourceName: "ADNOC",
    sourceCountry: "AE",
    sourceUrl: "https://www.adnoc.ae/en/ictvalue",
    description: "Abu Dhabi's national oil company. Construction, MEP, and maintenance contracts for oil & gas facilities, offshore platforms, and industrial complexes.",
    sectors: ["Oil & Gas", "Construction", "MEP"],
    deadline: "Ongoing",
    valueMax: "Multi-billion USD annually",
    status: "open",
  },
  // --- JORDAN ---
  {
    id: "jo-jlgc",
    title: "Jordan Loan Guarantee Corporation (JLGC)",
    type: "financing",
    sourceName: "JLGC",
    sourceCountry: "JO",
    sourceUrl: "https://www.jlgc.com/",
    description: "Loan guarantees for SMEs expanding in Jordan. Construction and contracting companies eligible for project-based guarantees.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  // --- EGYPT ---
  {
    id: "eg-nac",
    title: "Egypt New Administrative Capital — Construction Packages",
    type: "tender",
    sourceName: "ACUD (Administrative Capital for Urban Development)",
    sourceCountry: "EG",
    sourceUrl: "https://www.acud.eg/",
    description: "$58B new administrative capital project. Construction, MEP, and infrastructure packages for government buildings, residential, and commercial zones.",
    sectors: ["Construction", "Infrastructure", "MEP"],
    deadline: "Ongoing phases",
    valueMax: "$58B total project",
    status: "open",
  },
];

// =============================================================================
// MATCHES — SCORED AGAINST AL MOAYYED CONTRACTING GROUP
// =============================================================================

export const matchesAlMoayyed: Match[] = [
  {
    id: "m-acg-1",
    companyId: "almoayyed",
    opportunityId: "bh-tender-board",
    opportunityTitle: "Bahrain Tender Board — Government Procurement",
    opportunityType: "tender",
    sourceName: "Bahrain Tender Board",
    sourceCountry: "BH",
    combinedScore: 97,
    eligibilityScore: 100,
    relevanceScore: 98,
    competitivenessScore: 92,
    recommendation: "strong_match",
    summary: "AA-grade contractor with 54 years of history and landmark Bahrain government project experience. Highest possible qualification for government tenders.",
    keyFactors: [
      "AA Grade — highest Ministry of Works classification",
      "Completed BIA Terminal, F1 Circuit, Ministry of Housing projects",
      "6,500+ employees — full capacity for major government contracts",
      "Established government relationship through decades of projects",
    ],
  },
  {
    id: "m-acg-2",
    companyId: "almoayyed",
    opportunityId: "sa-etimad",
    opportunityTitle: "ETIMAD — Saudi Government eProcurement",
    opportunityType: "tender",
    sourceName: "Saudi Ministry of Finance",
    sourceCountry: "SA",
    combinedScore: 88,
    eligibilityScore: 85,
    relevanceScore: 95,
    competitivenessScore: 82,
    recommendation: "strong_match",
    summary: "Vision 2030 is generating the largest construction pipeline in history. ACG's capabilities in civil, MEP, and FM are directly applicable. Regional registration required.",
    keyFactors: [
      "Construction capabilities directly match Vision 2030 needs",
      "MEP and FM services applicable to mega-projects",
      "GCC-based company can leverage free trade agreements",
      "Would need Saudi contractor registration/partnership",
    ],
  },
  {
    id: "m-acg-3",
    companyId: "almoayyed",
    opportunityId: "sa-rcrc-neom",
    opportunityTitle: "NEOM — The Line & Related Projects",
    opportunityType: "tender",
    sourceName: "NEOM Company / PIF",
    sourceCountry: "SA",
    combinedScore: 85,
    eligibilityScore: 78,
    relevanceScore: 95,
    competitivenessScore: 80,
    recommendation: "strong_match",
    summary: "$500B+ mega-project with massive MEP, civil, and FM subcontracting packages. ACG could partner with Tier-1 contractors for specialized packages.",
    keyFactors: [
      "MEP and civil works capabilities directly applicable",
      "FM division could secure post-construction O&M contracts",
      "AMAS Island JV experience shows capability for mega-project partnerships",
      "Data center construction experience relevant to NEOM tech infrastructure",
    ],
  },
  {
    id: "m-acg-4",
    companyId: "almoayyed",
    opportunityId: "bh-tamkeen-enterprise",
    opportunityTitle: "Tamkeen Enterprise Support Program",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 84,
    eligibilityScore: 90,
    relevanceScore: 82,
    competitivenessScore: 78,
    recommendation: "strong_match",
    summary: "50% cost coverage for software, marketing, and services. ACG could use this for BIM software adoption, ERP upgrades, or digital marketing for the FM/cleaning divisions.",
    keyFactors: [
      "Bahrain-registered with active CR — meets base eligibility",
      "Digital transformation of construction operations eligible",
      "Marketing support for FM/cleaning/security service lines",
      "Software and technology investment support",
    ],
  },
  {
    id: "m-acg-5",
    companyId: "almoayyed",
    opportunityId: "bh-tamkeen-nep",
    opportunityTitle: "National Employment Program 3.0",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 91,
    eligibilityScore: 95,
    relevanceScore: 90,
    competitivenessScore: 88,
    recommendation: "strong_match",
    summary: "As one of Bahrain's largest private employers with 6,500+ staff, ACG is a prime candidate. Wage subsidies directly reduce labor costs across all divisions.",
    keyFactors: [
      "6,500+ employees — massive potential for Bahranization wage subsidies",
      "Multiple divisions (construction, FM, cleaning, security) all eligible",
      "Hospitality/construction among Tamkeen priority sectors",
      "Up to 36 months wage support per hire",
    ],
  },
  {
    id: "m-acg-6",
    companyId: "almoayyed",
    opportunityId: "sa-red-sea",
    opportunityTitle: "The Red Sea Project & AMAALA",
    opportunityType: "tender",
    sourceName: "Red Sea Global / PIF",
    sourceCountry: "SA",
    combinedScore: 83,
    eligibilityScore: 75,
    relevanceScore: 92,
    competitivenessScore: 80,
    recommendation: "strong_match",
    summary: "Luxury hospitality construction and landscaping. ACG's combined construction + landscaping + FM capabilities create a unique full-lifecycle value proposition.",
    keyFactors: [
      "Hotel/resort construction experience from Bahrain projects",
      "Landscaping division relevant to resort developments",
      "FM services create post-construction recurring revenue opportunity",
      "MEP for luxury hospitality is a proven ACG strength",
    ],
  },
  {
    id: "m-acg-7",
    companyId: "almoayyed",
    opportunityId: "og-bapco",
    opportunityTitle: "BAPCO Energies — Procurement",
    opportunityType: "tender",
    sourceName: "BAPCO Energies",
    sourceCountry: "BH",
    combinedScore: 90,
    eligibilityScore: 95,
    relevanceScore: 88,
    competitivenessScore: 85,
    recommendation: "strong_match",
    summary: "Bahrain's national oil company. ACG has local presence, AA-grade status, and construction/FM capabilities suitable for refinery maintenance and facility construction.",
    keyFactors: [
      "Local Bahrain-based — proximity advantage",
      "Industrial construction and MEP capabilities",
      "FM and cleaning services for industrial facilities",
      "ISO 14001 environmental certification",
    ],
  },
  {
    id: "m-acg-8",
    companyId: "almoayyed",
    opportunityId: "og-aramco",
    opportunityTitle: "Saudi Aramco — iSupplier Portal",
    opportunityType: "tender",
    sourceName: "Saudi Aramco",
    sourceCountry: "SA",
    combinedScore: 80,
    eligibilityScore: 72,
    relevanceScore: 90,
    competitivenessScore: 76,
    recommendation: "good_match",
    summary: "World's largest oil company with massive annual construction spend. ACG would need IKTVA qualification but capabilities are directly relevant.",
    keyFactors: [
      "Construction and MEP capabilities match Aramco needs",
      "ISO certifications support pre-qualification",
      "Would need In-Kingdom Total Value Add (IKTVA) registration",
      "JV with Saudi partner would strengthen bid",
    ],
  },
  {
    id: "m-acg-9",
    companyId: "almoayyed",
    opportunityId: "bh-tamkeen-digital",
    opportunityTitle: "Digital Transformation Support",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 82,
    eligibilityScore: 90,
    relevanceScore: 80,
    competitivenessScore: 75,
    recommendation: "good_match",
    summary: "BIM, ERP, IoT, and digital twin adoption for construction. ACG's scale makes digital transformation investment highly impactful and fundable.",
    keyFactors: [
      "BIM implementation across construction projects",
      "Fleet management digitization for transport division",
      "IoT integration for facility management services",
      "Data center construction experience shows tech capability",
    ],
  },
  {
    id: "m-acg-10",
    companyId: "almoayyed",
    opportunityId: "bh-export-finance",
    opportunityTitle: "Export Bahrain Financing",
    opportunityType: "financing",
    sourceName: "Export Bahrain",
    sourceCountry: "BH",
    combinedScore: 78,
    eligibilityScore: 85,
    relevanceScore: 75,
    competitivenessScore: 72,
    recommendation: "good_match",
    summary: "Export financing to support GCC expansion. Subsidized profit rates up to 70% for international market entry — directly applicable to Saudi and UAE project bids.",
    keyFactors: [
      "Bahrain-registered with export potential",
      "GCC expansion for construction services",
      "Export credit insurance for international contracts",
      "BD 1M financing available for overseas business development",
    ],
  },
  {
    id: "m-acg-11",
    companyId: "almoayyed",
    opportunityId: "ml-isdb",
    opportunityTitle: "Islamic Development Bank — Project Finance",
    opportunityType: "financing",
    sourceName: "IsDB",
    sourceCountry: "International",
    combinedScore: 75,
    eligibilityScore: 80,
    relevanceScore: 75,
    competitivenessScore: 68,
    recommendation: "good_match",
    summary: "IsDB-financed infrastructure projects across 57 OIC member countries. ACG can bid on construction packages for IsDB-funded projects in the region.",
    keyFactors: [
      "Bahrain is IsDB member country",
      "Infrastructure and construction are IsDB priority sectors",
      "Regional experience applicable to development bank-funded projects",
      "Sharia-compliant financing aligns with group values",
    ],
  },
  {
    id: "m-acg-12",
    companyId: "almoayyed",
    opportunityId: "ae-etihad-rail",
    opportunityTitle: "Etihad Rail — National Railway",
    opportunityType: "tender",
    sourceName: "Etihad Rail",
    sourceCountry: "AE",
    combinedScore: 76,
    eligibilityScore: 70,
    relevanceScore: 82,
    competitivenessScore: 74,
    recommendation: "good_match",
    summary: "$11B national railway with station buildings, depot construction, and MEP packages. ACG's civil and MEP capabilities are directly applicable.",
    keyFactors: [
      "Station building construction within ACG capabilities",
      "MEP for railway facilities",
      "Could partner with rail-specialist main contractor",
      "FM services for operational stations post-completion",
    ],
  },
  {
    id: "m-acg-13",
    companyId: "almoayyed",
    opportunityId: "eg-nac",
    opportunityTitle: "Egypt New Administrative Capital",
    opportunityType: "tender",
    sourceName: "ACUD",
    sourceCountry: "EG",
    combinedScore: 70,
    eligibilityScore: 65,
    relevanceScore: 80,
    competitivenessScore: 63,
    recommendation: "possible_match",
    summary: "$58B new capital project. Massive construction packages. ACG would need Egypt entity/partnership but capabilities are relevant. Higher competition expected.",
    keyFactors: [
      "Largest urban construction project in the Middle East",
      "Government buildings, residential, and commercial construction",
      "Would need Egyptian JV partner or entity establishment",
      "Higher competition from Egyptian and international contractors",
    ],
  },
  {
    id: "m-acg-14",
    companyId: "almoayyed",
    opportunityId: "sa-roshn",
    opportunityTitle: "ROSHN Housing Developments",
    opportunityType: "tender",
    sourceName: "ROSHN / PIF",
    sourceCountry: "SA",
    combinedScore: 82,
    eligibilityScore: 78,
    relevanceScore: 88,
    competitivenessScore: 78,
    recommendation: "strong_match",
    summary: "PIF-backed residential developer. ACG's AMAS Island housing experience (682 apartments, $166.8M) is directly transferable. FM services for community management.",
    keyFactors: [
      "AMAS Island housing project proves mass residential construction capability",
      "East Sitra housing (546 villas) further validates capability",
      "FM services applicable to community management post-completion",
      "JV approach (as with Airolink on AMAS) could work here",
    ],
  },
  {
    id: "m-acg-15",
    companyId: "almoayyed",
    opportunityId: "bh-tamkeen-training",
    opportunityTitle: "Professional Training & Certification",
    opportunityType: "training",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 86,
    eligibilityScore: 95,
    relevanceScore: 80,
    competitivenessScore: 82,
    recommendation: "strong_match",
    summary: "With 6,500+ employees, training subsidies for professional certifications (safety, quality, project management) have massive ROI potential across all divisions.",
    keyFactors: [
      "6,500+ employee base creates enormous training subsidy opportunity",
      "Safety certifications (NEBOSH, IOSH) for construction workforce",
      "Project management (PMP, PRINCE2) for management staff",
      "Already achieved 100M hours without LTI — training investment pays off",
    ],
  },
];

// =============================================================================
// MATCHES — SCORED AGAINST NORDIC GROUP (existing)
// =============================================================================

export const matchesNordic: Match[] = [
  {
    id: "m-ng-1",
    companyId: "nordic",
    opportunityId: "bh-bdb-sme",
    opportunityTitle: "BDB SME Fund",
    opportunityType: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    combinedScore: 86,
    eligibilityScore: 90,
    relevanceScore: 85,
    competitivenessScore: 80,
    recommendation: "strong_match",
    summary: "Tourism is one of BDB's 7 priority sectors. Fixed asset financing could fund property improvements or expansion.",
    keyFactors: [
      "Tourism is priority sector for BDB SME Fund",
      "Fixed asset financing for property improvements",
      "Sharia-compliant with Tamkeen rate subsidy",
      "2+ years operations meets eligibility threshold",
    ],
  },
  {
    id: "m-ng-2",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-enterprise",
    opportunityTitle: "Tamkeen Enterprise Support Program",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 79,
    eligibilityScore: 85,
    relevanceScore: 78,
    competitivenessScore: 72,
    recommendation: "good_match",
    summary: "Covers marketing, branding, software costs up to 50%. Directly applicable to hotel marketing and property management systems.",
    keyFactors: [
      "50% cost coverage for marketing and branding",
      "Property management software eligible",
      "Website and booking system upgrades",
      "Active Bahrain CR required — confirmed",
    ],
  },
  {
    id: "m-ng-3",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-nep",
    opportunityTitle: "National Employment Program 3.0",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 78,
    eligibilityScore: 92,
    relevanceScore: 70,
    competitivenessScore: 75,
    recommendation: "good_match",
    summary: "Wage subsidies for Bahraini employees. Hospitality is a major employer — multi-property operator can absorb new hires across 3 properties.",
    keyFactors: [
      "Hospitality major employer of Bahrainis",
      "3 properties can distribute new hires",
      "Up to 36 months wage support",
      "Accommodation & Food Services is top Tamkeen sector",
    ],
  },
  {
    id: "m-ng-4",
    companyId: "nordic",
    opportunityId: "bh-export-finance",
    opportunityTitle: "Export Bahrain Financing",
    opportunityType: "financing",
    sourceName: "Export Bahrain",
    sourceCountry: "BH",
    combinedScore: 62,
    eligibilityScore: 70,
    relevanceScore: 55,
    competitivenessScore: 60,
    recommendation: "possible_match",
    summary: "Could support GCC tourism marketing campaigns or franchise expansion. Less directly applicable than other programs but worth exploring.",
    keyFactors: [
      "Tourism marketing to GCC source markets",
      "Franchise or management contract export potential",
      "Lower relevance — primarily domestic operator",
      "Credit insurance for any international contracts",
    ],
  },
  {
    id: "m-ng-5",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-training",
    opportunityTitle: "Professional Training & Certification",
    opportunityType: "training",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 75,
    eligibilityScore: 88,
    relevanceScore: 72,
    competitivenessScore: 65,
    recommendation: "good_match",
    summary: "Hospitality certifications for staff — food safety, hotel management, spa therapy. Directly improves service quality across all 3 properties.",
    keyFactors: [
      "Food safety and hygiene certifications",
      "Hotel management professional training",
      "Spa therapy and wellness certifications",
      "Multi-property staff can all benefit",
    ],
  },
  {
    id: "m-ng-6",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-digital",
    opportunityTitle: "Digital Transformation Support",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 73,
    eligibilityScore: 85,
    relevanceScore: 68,
    competitivenessScore: 65,
    recommendation: "good_match",
    summary: "Fund adoption of hotel PMS, booking engines, revenue management software. Nordic already uses STAAH — could upgrade to full-stack hospitality tech.",
    keyFactors: [
      "Already uses STAAH booking engine — shows tech readiness",
      "PMS and revenue management system upgrades",
      "Guest experience digitization (app, self-check-in)",
      "Marketing automation and CRM tools",
    ],
  },
];

// Helper to get all matches for a company
export function getMatchesForCompany(companyId: string): Match[] {
  if (companyId === "almoayyed") return matchesAlMoayyed;
  if (companyId === "nordic") return matchesNordic;
  return [];
}

// Helper to get all opportunities relevant to a company's matches
export function getOpportunitiesForCompany(companyId: string): Opportunity[] {
  const matches = getMatchesForCompany(companyId);
  const oppIds = new Set(matches.map((m) => m.opportunityId));
  return opportunities.filter((o) => oppIds.has(o.id));
}
