// =============================================================================
// REAL RESEARCH DATA — Al Moayyed Contracting Group & Nordic Group
// =============================================================================

export interface CompanyProfile {
  id: string;
  name: string;
  websiteUrl: string;
  aiSummary: string;
  primarySector: string;
  secondarySectors: string[];
  country: string;
  city: string;
  sizeCategory: string;
  employeeRange: string;
  yearsInOperation: number;
  ownershipType: string;
  capabilities: string[];
  productsServices: string[];
  certifications: string[];
  keyProjects?: string[];
  leadership?: { name: string; role: string }[];
  geographicPresence?: string[];
  financialInfo?: {
    estimatedRevenue?: string;
    revenueSource?: string;
    contractorGrade?: string;
    majorContracts?: { project: string; value: string; client: string }[];
    marketPosition?: string;
    marketShare?: string;
    industryBenchmarks?: { metric: string; value: string }[];
    bankingRelationships?: string[];
    awards?: string[];
    parentCompany?: string;
    subsidiaries?: string[];
    totalGroupEmployees?: string;
    forbesRanking?: string;
  };
  confidenceScores: Record<string, number>;
}

export interface Opportunity {
  id: string;
  title: string;
  type: "grant" | "financing" | "tender" | "rfp" | "training" | "incentive";
  sourceName: string;
  sourceCountry: string;
  sourceUrl?: string;
  description: string;
  sectors: string[];
  deadline: string;
  valueMax: string;
  status: "open" | "upcoming" | "closing_soon";
}

export interface Match {
  id: string;
  companyId: string;
  opportunityId: string;
  opportunityTitle: string;
  opportunityType: string;
  sourceName: string;
  sourceCountry: string;
  combinedScore: number;
  eligibilityScore: number;
  relevanceScore: number;
  competitivenessScore: number;
  recommendation: string;
  summary: string;
  keyFactors: string[];
}

// =============================================================================
// COMPANY PROFILES
// =============================================================================

export const companies: Record<string, CompanyProfile> = {
  nordic: {
    id: "nordic",
    name: "Nordic Holding W.L.L. (Nordic Group of Hotels)",
    websiteUrl: "nordicbh.com",
    aiSummary:
      "Nordic Holding W.L.L. operates as 'Nordic Group of Hotels' — a private Bahraini hospitality company established in December 2018, managing 3 properties totaling 176 keys. The group holds a unique market position as the operator of Bahrain's only luxury 4-star dry (alcohol-free) hotel (Nordic Palace), complemented by a family-villa resort (Nordic Resort, 5 min from Saudi Causeway) and a budget villa property (Nordic Gardens). Primary market is GCC families, particularly Saudi weekend travelers. All properties are halal-certified and listed on HalalBooking.com. The group previously operated as Dana Homes Resort before rebranding to Nordic in 2020. Revenue estimated at $5.5-7.0M annually across rooms, F&B, spa, and events.",
    primarySector: "Hospitality & Tourism",
    secondarySectors: [
      "Wellness & Spa",
      "Food & Beverage (Halal)",
      "MICE / Corporate Events",
      "Family Entertainment",
      "Halal Tourism",
    ],
    country: "BH",
    city: "Manama",
    sizeCategory: "sme",
    employeeRange: "150-250 (est.)",
    yearsInOperation: 7,
    ownershipType: "private-wll",
    capabilities: [
      "Multi-property hotel management (3 properties, 176 keys)",
      "Villa-style resort operations with private pools",
      "Full-service spa & wellness (body scrubs, facials, aromatherapy, steam room)",
      "F&B operations (restaurants, cafes, room service, buffet breakfast)",
      "MICE facilities (banquet hall, meeting rooms, AV-equipped conference spaces)",
      "Kids entertainment (water park, water slides, playgrounds)",
      "Halal/Muslim-friendly hospitality (dry hotels, ladies-only facilities)",
      "Multi-channel OTA distribution (Booking.com, Expedia, Agoda, HalalBooking, 12+ OTAs)",
      "GDS connectivity (Amadeus, Galileo, Sabre, WorldSpan)",
      "Revenue management & channel management (STAAH platform)",
      "Ramadan & Islamic holiday packages (Iftar, Suhoor)",
      "Corporate travel & event management",
    ],
    productsServices: [
      "Nordic Resort — 44 luxury family villas with private pools, kids water park, ladies pool (Al Hamala, 5 min from Saudi Causeway)",
      "Nordic Palace & Spa — 84 rooms/suites, 4-star dry hotel, full spa, MICE facilities, GDS-connected (Al Seef, Manama)",
      "Nordic Gardens — 48 bungalow-style 3BR villas on 74,800 sqft, gardens, pool (Jannusan/Budaiya)",
      "H Restaurant & Cafe (F&B at Nordic Palace)",
      "Full-Service Spa (treatments, steam, sauna, Jacuzzi)",
      "Banquet & Meeting Facilities (conferences, weddings, events)",
    ],
    certifications: [
      "4-Star Hotel Classification (Nordic Palace)",
      "Halal-Certified Dining (all properties)",
      "HalalBooking.com Verified Muslim-Friendly",
      "BTEA Listed (Bahrain Tourism)",
    ],
    keyProjects: [
      "Nordic Resort — Originally Dana Homes Resort, rebranded to Nordic 2020",
      "Nordic Palace & Spa — Bahrain's only luxury 4-star dry hotel",
      "Nordic Gardens — Newest property, recently renovated, Jannusan/Budaiya",
      "Multi-property expansion from 1 to 3 hotels in 3 years",
    ],
    leadership: [
      { name: "Samreen Khan", role: "Group Director of HR & Hotel Operations" },
      { name: "Ali Edrees", role: "Cluster Front Office & Revenue Manager / Acting Dir. Operations" },
      { name: "Hawra Ali", role: "Assistant Marketing Manager" },
      { name: "Roni Joynal", role: "Revenue and Reservations Manager" },
    ],
    geographicPresence: ["Bahrain (3 locations: Al Hamala, Al Seef, Jannusan)"],
    financialInfo: {
      estimatedRevenue: "~$5.5-7.0M/year (est.)",
      revenueSource: "Estimate based on public rate data, 176 keys, Bahrain market averages — private company, no published financials",
      marketPosition: "Mid-range 4-star segment. Only luxury dry (no-alcohol) hotel in Bahrain. Competes below Gulf Hotel, Ritz-Carlton, Four Seasons; above budget hotels.",
      marketShare: "~176 keys of Bahrain's 190+ hotel supply (~1% of keys, niche segment)",
      majorContracts: [
        { project: "Nordic Resort (44 villas)", value: "~$1.8M/yr room revenue (est.)", client: "GCC Leisure / Saudi Weekend" },
        { project: "Nordic Palace (84 rooms)", value: "~$2.0M/yr room revenue (est.)", client: "Business / Halal Tourism" },
        { project: "Nordic Gardens (48 villas)", value: "~$1.05M/yr room revenue (est.)", client: "Budget Families / Couples" },
      ],
      industryBenchmarks: [
        { metric: "Bahrain Hotel Occupancy Growth (H1 2024)", value: "+7% YoY" },
        { metric: "Bahrain ADR Growth (H1 2024)", value: "+2.6% YoY" },
        { metric: "Bahrain RevPAR Growth (H1 2024)", value: "+9.8% YoY" },
        { metric: "Total Bahrain Hotels", value: "190+ (18 five-star, 48 four-star)" },
        { metric: "Hotel Pipeline", value: "$10B+ / 12 new hotels by 2026" },
        { metric: "Bahrain Tourist Target 2030", value: "30 million visitors" },
        { metric: "Saudi Arrivals Share", value: "~58% of all visitors" },
        { metric: "Nordic Palace Booking.com Score", value: "7.9/10 (4,150 reviews)" },
        { metric: "Nordic Resort Booking.com Score", value: "8.2/10 (2,678 reviews)" },
      ],
      awards: [
        "Bahrain's Only Luxury 4-Star Dry Hotel (Nordic Palace)",
        "Listed on Bahrain.com Official Tourism Portal",
        "HalalBooking.com Verified Property (all 3 hotels)",
        "TripAdvisor #1 B&B/Inn in Al Hamala (Nordic Resort)",
      ],
      parentCompany: "Nordic Holding W.L.L. (est. December 2018)",
      totalGroupEmployees: "150-250 estimated (industry standard 0.8-1.5 staff per key)",
    },
    confidenceScores: {
      sector: 0.98,
      size: 0.75,
      capabilities: 0.92,
      years: 0.85,
      geography: 0.95,
      financial: 0.55,
    },
  },

  almoayyed: {
    id: "almoayyed",
    name: "Al Moayyed Contracting Group",
    websiteUrl: "almoayyedcg.com",
    aiSummary:
      "Al Moayyed Contracting Group (ACG) is one of Bahrain's largest AA-grade contractors with 27 specialized divisions, part of the Y.K. Almoayyed & Sons conglomerate (Forbes #51 Top Arab Family Businesses). Founded 1982, formally consolidated 1999, with 6,500+ employees across Bahrain (HQ), Saudi Arabia (Dammam office), UAE (Dubai MEP entity), and Qatar. ACG delivers vertically-integrated construction services from raw materials (National Concrete Company) through civil works, MEP, interiors, scaffolding, facility management, landscaping, cleaning, security, elevators (TK Elevator JV), piling (Simplex JV), and real estate. Landmark projects include Bahrain International Airport ($33.69M refurbishment), F1 Racing Circuit, Harbour Row ($150M), AMAS Island ($166.8M), Batelco Data Center, and the Rabigh 4 IWP in Saudi Arabia (with ACWA Power).",
    primarySector: "Construction & Contracting",
    secondarySectors: [
      "Facility Management",
      "Real Estate Development",
      "MEP Engineering",
      "Cleaning & Environmental Services",
      "Security Services",
      "Transportation & Logistics",
      "Landscaping & Pools",
      "Scaffolding & Access Solutions",
      "Elevator & Escalator Installation (TK Elevator JV)",
      "Piling & Foundations (Simplex JV)",
      "Aluminium & Glazing",
      "Interior Fit-Out & Joinery",
      "Lighting Design (TG Lighting JV)",
      "Concrete & Building Materials (NCC)",
    ],
    country: "BH",
    city: "Manama",
    sizeCategory: "large",
    employeeRange: "6,500+",
    yearsInOperation: 54,
    ownershipType: "family-conglomerate",
    capabilities: [
      "AA-Grade Civil & Building Construction",
      "Electromechanical (MEP) Engineering",
      "Interior Design & Fit-Out",
      "Scaffolding & Formwork Systems",
      "Integrated Facility Management",
      "Industrial & Commercial Cleaning",
      "Landscaping & Irrigation",
      "Manned Security & Surveillance",
      "Fleet Management & Transportation",
      "Real Estate Development & Investment",
      "Data Center Construction",
      "Power Plant & IWPP Construction",
      "Solar PV Installation (via Almoayyed Solar)",
      "Ready-Mix Concrete Production (via NCC)",
      "Precast Concrete Manufacturing",
    ],
    productsServices: [
      "Civil & Building Construction (high-rise, residential, commercial, industrial)",
      "Electromechanical Engineering (HVAC, electrical, plumbing, fire fighting)",
      "Interior Fit-Out & Finishing Works",
      "Scaffolding & Temporary Works",
      "Facility Management (hard & soft services)",
      "Cleaning Services (industrial, commercial, residential)",
      "Landscaping & Grounds Maintenance",
      "Security Services (guarding, CCTV, access control)",
      "Transportation & Fleet Services",
      "Real Estate Development (Almoayyed Tower, The Garnet)",
    ],
    certifications: [
      "ISO 9001:2015 (Quality Management)",
      "ISO 14001:2015 (Environmental Management)",
      "BS OHSAS 18001:2007 (Health & Safety)",
      "AA Grade — Bahrain Ministry of Works (highest classification)",
    ],
    keyProjects: [
      "Harbour Row, Bahrain Financial Harbour (~$150M, 450 residential units)",
      "AMAS Island Housing (~$166.8M, 682 apartments — JV with Airolink)",
      "Almoayyed Tower, Seef (BD 20M, 47-storey commercial tower)",
      "East Sitra Housing Project (546 social villas)",
      "Bahrain International Airport — New Passenger Terminal",
      "Formula 1 Racing Circuit, Bahrain",
      "Gulf International Convention Centre",
      "Gulf International Bank Headquarters",
      "Batelco White Space Data Center (first solar-powered in Bahrain)",
      "Al Dur II IWPP (10% equity stake — power & water project)",
    ],
    leadership: [
      { name: "Mohammed Farouk Almoayyed", role: "Chairman (since March 2025)" },
      { name: "Fareed Yousuf Almoayyed", role: "Deputy Chairman" },
      { name: "Mona Yousuf Almoayyed", role: "Managing Director" },
    ],
    geographicPresence: ["Bahrain (HQ)", "Saudi Arabia (Dammam office)", "UAE Dubai (AEMC LLC)", "Qatar (AC projects)"],
    financialInfo: {
      estimatedRevenue: "~$576.5 million (2025 est.)",
      revenueSource: "Dun & Bradstreet / ZoomInfo estimates — privately held, unaudited",
      contractorGrade: "AA — Bahrain Ministry of Works (highest classification)",
      majorContracts: [
        { project: "Harbour Row, Bahrain Financial Harbour", value: "~$150M", client: "GFH Real Estate" },
        { project: "AMAS Island Housing (Islands 10 & 11)", value: "~$166.8M", client: "Ministry of Housing, Bahrain" },
        { project: "Almoayyed Tower, Seef", value: "~$53M (BD 20M)", client: "Almoayyed Properties" },
        { project: "East Sitra Housing Project", value: "Undisclosed", client: "Ministry of Housing" },
        { project: "Batelco White Space Data Center", value: "Undisclosed", client: "Batelco / Beyon Group" },
      ],
      marketPosition: "Top 3-5 contractor in Bahrain. Estimated larger than publicly listed Nass Corporation (~$401M revenue).",
      marketShare: "~10-12% of Bahrain's $3.2B construction market (construction-specific revenue est. $300-400M)",
      industryBenchmarks: [
        { metric: "Bahrain Construction Market Size (2025)", value: "$3.17-3.4 billion" },
        { metric: "Market CAGR (2025-2031)", value: "4.13%" },
        { metric: "Projected Market Size (2031)", value: "$4.04 billion" },
        { metric: "Residential Share", value: "~45%" },
        { metric: "Commercial Share", value: "~30%" },
        { metric: "Infrastructure Pipeline", value: "$30 billion multi-year" },
      ],
      bankingRelationships: [
        "National Bank of Bahrain (NBB) — Chairman was Farouk Y. Almoayyed (2011-2024)",
        "Bahrain National Holding (BNH) — Farouk Almoayyed serves as Chairman",
        "BMMI BSC — Mohammed Almoayyed is Director (since 2004)",
        "National Finance House — Mohammed Almoayyed is Vice Chairman (since 2006)",
      ],
      awards: [
        "Forbes #51 Top 100 Arab Family Businesses (2024) — #1 in Bahrain",
        "100 Million Employee Hours Without Lost Time Injury (April 2024)",
        "Ministry of Works: Recommended for any high-specification project",
        "Bahrain's First Solar-Powered White Space Data Center (2024)",
      ],
      parentCompany: "Y.K. Almoayyed & Sons BSC (c) — Founded 1940",
      subsidiaries: [
        "Almoayyed Properties (real estate)",
        "National Concrete Company — NCC (ready-mix, precast)",
        "Almoayyed International Group (ICT, solar, engineering, F&B)",
        "Almoayyed Motors (Ford, Lincoln)",
        "Almoayyed Air Conditioning",
        "Almoayyed Express Lift Co.",
        "Ashrafs W.L.L.",
      ],
      totalGroupEmployees: "13,000+ across all group entities",
      forbesRanking: "#51 Top 100 Arab Family Businesses — #1 in Bahrain",
    },
    confidenceScores: {
      sector: 0.98,
      size: 0.95,
      capabilities: 0.97,
      years: 0.99,
      geography: 0.95,
      financial: 0.75,
    },
  },
};

// =============================================================================
// OPPORTUNITIES — REAL DATA FROM MIDDLE EAST RESEARCH
// =============================================================================

export const opportunities: Opportunity[] = [
  // --- BAHRAIN ---
  {
    id: "bh-tamkeen-enterprise",
    title: "Tamkeen Enterprise Support Program",
    type: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/programs/",
    description: "Grants covering up to 50% of eligible costs including software, services, hardware, marketing, and branding within an approved cap. Designed for growing Bahraini businesses.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Up to 50% of costs",
    status: "open",
  },
  {
    id: "bh-tamkeen-nep",
    title: "National Employment Program 3.0",
    type: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/programs/national-employment-program-3-0/",
    description: "Wage subsidies for Bahraini job seekers and fresh graduates for up to 36 months. Incentivizes private sector hiring of Bahrainis in priority sectors.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Wage subsidy up to 36 months",
    status: "open",
  },
  {
    id: "bh-tamkeen-training",
    title: "Professional Training & Certification",
    type: "training",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/",
    description: "Funds professional certifications and skills development for Bahraini employees including technical, management, and leadership training programs.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Varies by program",
    status: "open",
  },
  {
    id: "bh-tamkeen-export",
    title: "Export / Overseas Expansion Program",
    type: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/",
    description: "Financial assistance for businesses looking to expand into international markets. Supports market entry, exhibitions, and business development abroad.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Varies",
    status: "open",
  },
  {
    id: "bh-tamkeen-digital",
    title: "Digital Transformation Support",
    type: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    sourceUrl: "https://www.tamkeen.bh/en/",
    description: "Support for digital transformation initiatives across Bahraini businesses. Over 8,400 institutions assisted to date.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Varies",
    status: "open",
  },
  {
    id: "bh-bdb-sme",
    title: "BDB SME Fund ($185M)",
    type: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    sourceUrl: "https://www.bdb-bh.com/",
    description: "Sharia-compliant financing with flexible repayment up to 5 years. Tamkeen subsidizes profit rates by up to 50%. Covers fixed assets and working capital for 7 strategic sectors.",
    sectors: ["Tourism", "Manufacturing", "Logistics", "IT", "Finance", "Health", "Education"],
    deadline: "Open (since Nov 2025)",
    valueMax: "Up to $185M fund",
    status: "open",
  },
  {
    id: "bh-bdb-finance",
    title: "BDB & Tamkeen Joint Finance",
    type: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    sourceUrl: "https://www.bdb-bh.com/",
    description: "Partnership financing with subsidized profit rates for SMEs. Covers business term loans, working capital, and growth financing.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  {
    id: "bh-bdb-invoice",
    title: "BDB Invoice Discounting (Tijara)",
    type: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    sourceUrl: "https://www.tijara.bh/",
    description: "Supply chain financing allowing SMEs to receive early payment on invoices from registered buyers. Recently launched with Alba as anchor buyer.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Based on invoices",
    status: "open",
  },
  {
    id: "bh-export-finance",
    title: "Export Bahrain Financing",
    type: "financing",
    sourceName: "Export Bahrain",
    sourceCountry: "BH",
    sourceUrl: "https://export.bh/",
    description: "Export financing up to BD 1 million with profit rate subsidies up to 70%. Includes export credit insurance, market intelligence, and trade facilitation.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "BD 1,000,000 (~$2.65M)",
    status: "open",
  },
  {
    id: "bh-tender-board",
    title: "Bahrain Tender Board — Government Procurement",
    type: "tender",
    sourceName: "Bahrain Tender Board",
    sourceCountry: "BH",
    sourceUrl: "https://etendering.tenderboard.gov.bh/",
    description: "All civilian government tenders above BD 10,000. Annual procurement volume ~BHD 3.2 billion. Registered vendors can bid on construction, infrastructure, and service contracts.",
    sectors: ["Construction", "Infrastructure", "Services", "IT"],
    deadline: "Ongoing — per tender",
    valueMax: "BHD 3.2B annual volume",
    status: "open",
  },
  {
    id: "bh-edb-investment",
    title: "EDB Investment Facilitation",
    type: "incentive",
    sourceName: "Bahrain Economic Development Board",
    sourceCountry: "BH",
    sourceUrl: "https://www.bahrainedb.com/",
    description: "Free facilitation service for investors: registration support, incentive packages (0% corporate tax, 100% foreign ownership, BIIP/BLZ free zone benefits), and operational setup.",
    sectors: ["Financial Services", "Manufacturing", "ICT", "Tourism", "Logistics"],
    deadline: "Always Open",
    valueMax: "Tax & duty incentives",
    status: "open",
  },
  {
    id: "bh-biip-incentives",
    title: "Bahrain International Investment Park (BIIP)",
    type: "incentive",
    sourceName: "BIIP / EDB",
    sourceCountry: "BH",
    sourceUrl: "https://www.bahrainedb.com/bahrain-international-investment-park",
    description: "0% import duty on raw materials & equipment, competitive lease rates, 100% foreign ownership, duty-free GCC/GAFTA access, 15% electricity discount for manufacturing.",
    sectors: ["Manufacturing", "Logistics", "Services"],
    deadline: "Always Open",
    valueMax: "Ongoing incentives",
    status: "open",
  },
  // --- SAUDI ARABIA ---
  {
    id: "sa-nidlp",
    title: "National Industrial Development & Logistics Program (NIDLP)",
    type: "incentive",
    sourceName: "Saudi Ministry of Industry",
    sourceCountry: "SA",
    sourceUrl: "https://www.vision2030.gov.sa/",
    description: "Part of Vision 2030, providing incentives, licensing facilitation, and investment support for industrial and logistics companies entering the Saudi market.",
    sectors: ["Construction", "Manufacturing", "Logistics", "Mining"],
    deadline: "Ongoing",
    valueMax: "Project-dependent",
    status: "open",
  },
  {
    id: "sa-sidf",
    title: "Saudi Industrial Development Fund (SIDF)",
    type: "financing",
    sourceName: "SIDF",
    sourceCountry: "SA",
    sourceUrl: "https://www.sidf.gov.sa/",
    description: "Long-term, low-cost financing for industrial, energy, mining, and logistics projects. Finances up to 75% of project cost with repayment up to 20 years.",
    sectors: ["Construction Materials", "Manufacturing", "Energy", "Mining"],
    deadline: "Open",
    valueMax: "Up to 75% of project cost",
    status: "open",
  },
  {
    id: "sa-monshaat",
    title: "Monsha'at SME Support Programs",
    type: "grant",
    sourceName: "Monsha'at (General Authority for SMEs)",
    sourceCountry: "SA",
    sourceUrl: "https://www.monshaat.gov.sa/",
    description: "Comprehensive SME support including financing access, advisory services, government procurement access, and contractor qualification support.",
    sectors: ["All Sectors"],
    deadline: "Rolling",
    valueMax: "Varies by program",
    status: "open",
  },
  {
    id: "sa-etimad",
    title: "ETIMAD — Saudi Government eProcurement",
    type: "tender",
    sourceName: "Ministry of Finance",
    sourceCountry: "SA",
    sourceUrl: "https://portal.etimad.sa/",
    description: "Unified Saudi government procurement portal. All ministry and government entity tenders published here. Massive construction pipeline under Vision 2030.",
    sectors: ["Construction", "Infrastructure", "IT", "Services"],
    deadline: "Ongoing — per tender",
    valueMax: "Billions SAR annually",
    status: "open",
  },
  {
    id: "sa-rcrc-neom",
    title: "NEOM — The Line & Related Projects",
    type: "tender",
    sourceName: "NEOM Company / PIF",
    sourceCountry: "SA",
    sourceUrl: "https://www.neom.com/",
    description: "$500B+ mega-project. Construction contracts for The Line, Trojena, Oxagon, Sindalah. MEP, civil, and specialist subcontracting packages available.",
    sectors: ["Construction", "MEP", "Infrastructure"],
    deadline: "Ongoing phases",
    valueMax: "$500B+ total project",
    status: "open",
  },
  {
    id: "sa-red-sea",
    title: "The Red Sea Project & AMAALA",
    type: "tender",
    sourceName: "Red Sea Global / PIF",
    sourceCountry: "SA",
    sourceUrl: "https://www.redseaglobal.com/",
    description: "Luxury tourism development with hotels, airports, and infrastructure. Construction packages for buildings, MEP, landscaping, and facility management.",
    sectors: ["Construction", "Hospitality", "MEP", "Landscaping"],
    deadline: "Ongoing phases",
    valueMax: "$10B+ combined",
    status: "open",
  },
  {
    id: "sa-diriyah",
    title: "Diriyah Gate Development",
    type: "tender",
    sourceName: "Diriyah Gate Development Authority",
    sourceCountry: "SA",
    sourceUrl: "https://www.dgda.gov.sa/",
    description: "$63B development on the outskirts of Riyadh. Cultural, hospitality, retail, and residential construction packages.",
    sectors: ["Construction", "Heritage", "Hospitality"],
    deadline: "Ongoing phases",
    valueMax: "$63B total",
    status: "open",
  },
  {
    id: "sa-roshn",
    title: "ROSHN Housing Developments",
    type: "tender",
    sourceName: "ROSHN / PIF",
    sourceCountry: "SA",
    sourceUrl: "https://www.roshn.sa/",
    description: "PIF-backed residential community developer. Multiple mega-communities across Saudi Arabia. Construction and FM packages for residential units and community infrastructure.",
    sectors: ["Construction", "Residential", "Facility Management"],
    deadline: "Ongoing",
    valueMax: "Multi-billion SAR",
    status: "open",
  },
  // --- UAE ---
  {
    id: "ae-khalifa-fund",
    title: "Khalifa Fund for Enterprise Development",
    type: "financing",
    sourceName: "Khalifa Fund",
    sourceCountry: "AE",
    sourceUrl: "https://www.khalifafund.gov.ae/",
    description: "SME financial support and training for businesses operating in or expanding to Abu Dhabi. Provides loans, equity, and advisory services.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies by program",
    status: "open",
  },
  {
    id: "ae-adgpg",
    title: "Abu Dhabi Government Procurement Gate",
    type: "tender",
    sourceName: "Abu Dhabi Government",
    sourceCountry: "AE",
    sourceUrl: "https://www.adgpg.gov.ae/",
    description: "Centralized procurement portal for Abu Dhabi government entities. Construction, infrastructure, and service contracts across all emirates.",
    sectors: ["Construction", "Infrastructure", "Services"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "ae-dubai-esupply",
    title: "Dubai eSupply Portal",
    type: "tender",
    sourceName: "Dubai Government",
    sourceCountry: "AE",
    sourceUrl: "https://esupply.dubai.gov.ae/",
    description: "Dubai government procurement portal. Tenders for construction, FM, cleaning, landscaping, and infrastructure maintenance.",
    sectors: ["Construction", "Facility Management", "Services"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "ae-etihad-rail",
    title: "Etihad Rail — National Railway",
    type: "tender",
    sourceName: "Etihad Rail",
    sourceCountry: "AE",
    sourceUrl: "https://www.etihadrail.ae/",
    description: "1,200km national railway network. Construction packages for stations, depots, civil works, and MEP across all emirates.",
    sectors: ["Construction", "Infrastructure", "MEP"],
    deadline: "Phase-dependent",
    valueMax: "$11B total project",
    status: "open",
  },
  // --- KUWAIT ---
  {
    id: "kw-nfund",
    title: "Kuwait National Fund for SME Development",
    type: "financing",
    sourceName: "National Fund for SME Development",
    sourceCountry: "KW",
    sourceUrl: "https://www.nationalfund.gov.kw/",
    description: "Financial support, training, and consulting for SMEs. Includes Mubader Plus workshops for entrepreneurs expanding in Kuwait.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  {
    id: "kw-capt",
    title: "Kuwait Central Agency for Public Tenders (CAPT)",
    type: "tender",
    sourceName: "CAPT",
    sourceCountry: "KW",
    sourceUrl: "https://capt.gov.kw/en/",
    description: "All Kuwaiti government tenders above 75,000 KD (~$248,500). Major infrastructure projects including Silk City, Kuwait Metro, and Al Mutlaa City.",
    sectors: ["Construction", "Infrastructure", "Services"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  // --- QATAR ---
  {
    id: "qa-monaqasat",
    title: "Qatar Monaqasat (Government eTendering)",
    type: "tender",
    sourceName: "Qatar Ministry of Finance",
    sourceCountry: "QA",
    sourceUrl: "https://monaqasat.mof.gov.qa/",
    description: "All Qatari government ministry tenders. Post-World Cup infrastructure and Qatar National Vision 2030 projects in construction and services.",
    sectors: ["Construction", "Infrastructure", "Services"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "qa-qdb",
    title: "Qatar Development Bank Programs",
    type: "financing",
    sourceName: "Qatar Development Bank",
    sourceCountry: "QA",
    sourceUrl: "https://www.qdb.qa/",
    description: "SME financing, advisory services, and market access support. Includes Al Dhameen credit guarantee scheme and Tasdeer export support.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  // --- OMAN ---
  {
    id: "om-tender-board",
    title: "Oman Tender Board — Government Procurement",
    type: "tender",
    sourceName: "Oman Tender Board",
    sourceCountry: "OM",
    sourceUrl: "https://etendering.tenderboard.gov.om/",
    description: "Government tenders across all sectors. Major projects in Duqm Special Economic Zone, Oman Rail, and tourism developments.",
    sectors: ["Construction", "Infrastructure", "Oil & Gas"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "om-riyada",
    title: "Riyada (Public Authority for SME Development)",
    type: "financing",
    sourceName: "Riyada",
    sourceCountry: "OM",
    sourceUrl: "https://www.riyada.om/",
    description: "SME support including financing, incubation, and business advisory. Al Raffd Fund provides microfinance and SME loans.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  // --- MULTILATERAL ---
  {
    id: "ml-isdb",
    title: "Islamic Development Bank (IsDB) — Project Finance",
    type: "financing",
    sourceName: "Islamic Development Bank",
    sourceCountry: "International",
    sourceUrl: "https://www.isdb.org/",
    description: "Sharia-compliant project financing, trade finance, and technical assistance for member countries. Infrastructure and construction are priority sectors.",
    sectors: ["Infrastructure", "Construction", "Energy", "Water"],
    deadline: "Project-based",
    valueMax: "Multi-billion USD portfolio",
    status: "open",
  },
  {
    id: "ml-afesd",
    title: "Arab Fund for Economic & Social Development (AFESD)",
    type: "financing",
    sourceName: "AFESD",
    sourceCountry: "International",
    sourceUrl: "https://www.arabfund.org/",
    description: "Concessional loans for infrastructure, energy, and industrial development projects across Arab countries. Active in construction and industrial sectors.",
    sectors: ["Infrastructure", "Construction", "Energy", "Industry"],
    deadline: "Project-based",
    valueMax: "Multi-million KD per project",
    status: "open",
  },
  {
    id: "ml-kfaed",
    title: "Kuwait Fund for Arab Economic Development (KFAED)",
    type: "financing",
    sourceName: "KFAED",
    sourceCountry: "KW",
    sourceUrl: "https://www.kuwait-fund.org/",
    description: "Development loans for infrastructure, transport, energy, and construction projects in developing countries. Procurement open to international contractors.",
    sectors: ["Infrastructure", "Construction", "Transport", "Energy"],
    deadline: "Project-based",
    valueMax: "Per project allocation",
    status: "open",
  },
  {
    id: "ml-adfd",
    title: "Abu Dhabi Fund for Development (ADFD)",
    type: "financing",
    sourceName: "ADFD",
    sourceCountry: "AE",
    sourceUrl: "https://www.adfd.ae/",
    description: "Development finance for infrastructure projects globally. Provides concessional loans, grants, and equity investments with construction procurement opportunities.",
    sectors: ["Infrastructure", "Construction", "Energy", "Housing"],
    deadline: "Project-based",
    valueMax: "AED 3B+ annual commitments",
    status: "open",
  },
  {
    id: "ml-sfd",
    title: "Saudi Fund for Development (SFD)",
    type: "financing",
    sourceName: "SFD",
    sourceCountry: "SA",
    sourceUrl: "https://www.sfd.gov.sa/",
    description: "Development loans for global projects with procurement opportunities for construction and infrastructure contractors.",
    sectors: ["Infrastructure", "Construction", "Energy"],
    deadline: "Project-based",
    valueMax: "Per project",
    status: "open",
  },
  // --- OIL & GAS PROCUREMENT ---
  {
    id: "og-bapco",
    title: "BAPCO Energies — Procurement",
    type: "tender",
    sourceName: "BAPCO Energies",
    sourceCountry: "BH",
    sourceUrl: "https://www.bapco.net/",
    description: "Bahrain's national oil company procurement. Construction, maintenance, and facility management contracts for refineries and production facilities.",
    sectors: ["Oil & Gas", "Construction", "Facility Management"],
    deadline: "Ongoing",
    valueMax: "Per tender",
    status: "open",
  },
  {
    id: "og-aramco",
    title: "Saudi Aramco — iSupplier Portal",
    type: "tender",
    sourceName: "Saudi Aramco",
    sourceCountry: "SA",
    sourceUrl: "https://www.saudiaramco.com/",
    description: "World's largest oil company. Massive construction, MEP, and FM contracts. Contractor pre-qualification (IKTVA) for local and international companies.",
    sectors: ["Oil & Gas", "Construction", "MEP", "Facility Management"],
    deadline: "Ongoing",
    valueMax: "Multi-billion USD annually",
    status: "open",
  },
  {
    id: "og-adnoc",
    title: "ADNOC — Procurement & Supplier Portal",
    type: "tender",
    sourceName: "ADNOC",
    sourceCountry: "AE",
    sourceUrl: "https://www.adnoc.ae/en/ictvalue",
    description: "Abu Dhabi's national oil company. Construction, MEP, and maintenance contracts for oil & gas facilities, offshore platforms, and industrial complexes.",
    sectors: ["Oil & Gas", "Construction", "MEP"],
    deadline: "Ongoing",
    valueMax: "Multi-billion USD annually",
    status: "open",
  },
  // --- BAHRAIN MEGA ---
  {
    id: "bh-metro",
    title: "Bahrain Metro — PPP (Red & Blue Lines)",
    type: "tender",
    sourceName: "Ministry of Transportation",
    sourceCountry: "BH",
    sourceUrl: "https://www.tenderboard.gov.bh/",
    description: "$2B+ metro system. Phase 1: Red and Blue lines, 29km, 20 stations. PPP model (DBFOMT, ~35-year contract). Pre-qualified consortia being re-engaged.",
    sectors: ["Construction", "Infrastructure", "MEP"],
    deadline: "Pre-qualification active",
    valueMax: "$2 billion+",
    status: "upcoming",
  },
  {
    id: "bh-ewa-substations",
    title: "EWA — New 66kV Substations & Renewable Energy",
    type: "tender",
    sourceName: "Electricity & Water Authority",
    sourceCountry: "BH",
    sourceUrl: "https://www.ewa.bh/",
    description: "2 new 66kV substations in 2026, 4 in 2027, 3 more after. 300 MW renewable target by end 2026. New SWRO desalination plant on Hawar Island.",
    sectors: ["Energy", "Construction", "MEP"],
    deadline: "Phased 2026-2028",
    valueMax: "Multi-million BHD per phase",
    status: "open",
  },
  {
    id: "bh-housing-khalifa",
    title: "Madinat Khalifa Housing — 3,000+ Units",
    type: "tender",
    sourceName: "Ministry of Housing",
    sourceCountry: "BH",
    sourceUrl: "https://www.tenderboard.gov.bh/",
    description: "Tender expected for 3,000+ housing units in Madinat Khalifa. Active projects in Madinat Al Hidd, Madinat Salman, and Madinat Sitra within 2025-2026 budget.",
    sectors: ["Construction", "Residential"],
    deadline: "Upcoming 2026",
    valueMax: "Multi-million BHD",
    status: "upcoming",
  },
  // --- SAUDI MEGA ---
  {
    id: "sa-ksia",
    title: "King Salman International Airport (KSIA)",
    type: "tender",
    sourceName: "KSIADC",
    sourceCountry: "SA",
    sourceUrl: "https://www.saudigulfprojects.com/",
    description: "$30B+ airport. Bechtel for 3 terminals, Parsons for airside, Samsung C&T/Nesma for construction. MEP subcontracting packages available under main contractors.",
    sectors: ["Construction", "MEP", "Infrastructure"],
    deadline: "Ongoing — subcontracting",
    valueMax: "$30 billion+ total",
    status: "open",
  },
  {
    id: "sa-diriyah-arena",
    title: "Diriyah Gate — Arena Block Phase 2 ($1.5B)",
    type: "tender",
    sourceName: "DGDA",
    sourceCountry: "SA",
    sourceUrl: "https://www.dgda.gov.sa/",
    description: "$1.5B contract for Arena Block: Diriyah Arena, 3 mixed-use office buildings, parking. Plus Red Line Metro extension (8.4km, $2.75B) to Diriyah.",
    sectors: ["Construction", "MEP", "Mixed-Use"],
    deadline: "Active construction",
    valueMax: "$1.5 billion (Arena Block)",
    status: "open",
  },
  {
    id: "sa-jeddah-tower",
    title: "Jeddah Tower — World's First 1km Structure",
    type: "tender",
    sourceName: "Jeddah Economic Company",
    sourceCountry: "SA",
    sourceUrl: "https://jeddahtower.online/",
    description: "Restarted Jan 2025. Reached 80th floor by Jan 2026, adding a floor every 3-4 days. Completion Aug 2028. Complex supertall MEP packages.",
    sectors: ["Construction", "MEP", "High-Rise"],
    deadline: "Active construction",
    valueMax: "$1.2B (tower) / $20B+ (full city)",
    status: "open",
  },
  {
    id: "sa-qiddiya",
    title: "Qiddiya Entertainment City & Q-Express Rail",
    type: "tender",
    sourceName: "Qiddiya Investment Company",
    sourceCountry: "SA",
    sourceUrl: "https://www.qiddiya.com/",
    description: "$8B+ entertainment city. Q-Express high-speed rail RFP expected H1 2026. Theme parks, sports venues, and hospitality under development.",
    sectors: ["Construction", "MEP", "Entertainment"],
    deadline: "RFP expected H1 2026",
    valueMax: "$8 billion+",
    status: "upcoming",
  },
  {
    id: "sa-renewable-14gw",
    title: "Saudi Renewable Energy — 14 GW (NREP Round 7)",
    type: "tender",
    sourceName: "SPPC / NREP",
    sourceCountry: "SA",
    sourceUrl: "https://www.powersaudiarabia.com.sa/",
    description: "4 solar projects (3.1 GW) + 2 wind projects (2.2 GW) to be awarded in 2026. $32B pipeline 2025-2030. Substation and BOP construction packages.",
    sectors: ["Energy", "Construction", "Electrical"],
    deadline: "2026 awards",
    valueMax: "$32 billion pipeline",
    status: "open",
  },
  {
    id: "sa-healthcare",
    title: "Saudi Healthcare Mega-Projects (SR260B allocation)",
    type: "tender",
    sourceName: "Ministry of Health / PIF",
    sourceCountry: "SA",
    sourceUrl: "https://portal.etimad.sa/",
    description: "SR260B ($69.3B) for health/social development. King Khalid Hospital (1,500 beds), King Abdullah Security Medical Cities, SEDRA health centers. 160,000 construction workers at peak 2026.",
    sectors: ["Construction", "Healthcare", "MEP"],
    deadline: "Ongoing",
    valueMax: "$69.3B allocation",
    status: "open",
  },
  // --- UAE MEGA ---
  {
    id: "ae-maktoum-airport",
    title: "Al Maktoum International Airport Expansion ($35B)",
    type: "tender",
    sourceName: "DAEP / Dubai Airports",
    sourceCountry: "AE",
    sourceUrl: "https://www.dubaiairports.ae/",
    description: "$35B expansion. Construction started Q2 2026. 5 parallel runways, 400+ gates, 260M passengers/year. World's largest airport. Phase 1 ready 2029.",
    sectors: ["Construction", "MEP", "Infrastructure"],
    deadline: "Active construction",
    valueMax: "$35 billion",
    status: "open",
  },
  {
    id: "ae-dubai-metro-blue",
    title: "Dubai Metro Blue Line (30km, 14 stations)",
    type: "tender",
    sourceName: "RTA Dubai",
    sourceCountry: "AE",
    sourceUrl: "https://www.rta.ae/",
    description: "30km new track, 14 new stations by 2029. Connecting Dubai Creek Harbour, International City, Silicon Oasis, Mirdif, Al Warqa. Station MEP packages.",
    sectors: ["Construction", "Infrastructure", "MEP"],
    deadline: "Under construction — 2029",
    valueMax: "Multi-billion AED",
    status: "open",
  },
  {
    id: "ae-fahid-island",
    title: "Fahid Island Development ($11B) — Aldar",
    type: "tender",
    sourceName: "Aldar Properties",
    sourceCountry: "AE",
    sourceUrl: "https://www.aldar.com/",
    description: "New $11B project between Yas and Saadiyat Islands. 11km coastline. Community infrastructure, residential, hospitality. Announced June 2025.",
    sectors: ["Construction", "Residential", "Hospitality"],
    deadline: "Early phases 2026+",
    valueMax: "$11 billion",
    status: "upcoming",
  },
  // --- QATAR ---
  {
    id: "qa-ashghal-5yr",
    title: "Qatar Ashghal — $22.2B Infrastructure Plan (2025-2029)",
    type: "tender",
    sourceName: "Ashghal (Public Works Authority)",
    sourceCountry: "QA",
    sourceUrl: "https://ashghal.gov.qa/",
    description: "$22.2B five-year plan: residential infrastructure, government buildings (health, education, sports). Strategic drainage tunnels and highways O&M ($969M awarded).",
    sectors: ["Construction", "Infrastructure", "MEP"],
    deadline: "2025-2029 program",
    valueMax: "$22.2 billion",
    status: "open",
  },
  {
    id: "qa-lusail-250b",
    title: "Lusail City — $250B Project Pipeline",
    type: "tender",
    sourceName: "Qatari Diar",
    sourceCountry: "QA",
    sourceUrl: "https://www.qataridiar.com/",
    description: "$250B pipeline. 65% infrastructure done, 67% private projects under construction. Huzoom, Qetaifan Island, Seef, Al Maha Island, Meryal Waterpark.",
    sectors: ["Construction", "Mixed-Use", "Hospitality"],
    deadline: "Ongoing phases",
    valueMax: "$250 billion pipeline",
    status: "open",
  },
  // --- JORDAN ---
  {
    id: "jo-aqaba",
    title: "Aqaba Special Economic Zone — Marsa Zayed & Smart City",
    type: "tender",
    sourceName: "ASEZA / AD Ports Group",
    sourceCountry: "JO",
    sourceUrl: "https://www.aseza.jo/",
    description: "Marsa Zayed waterfront (AD Ports/Majid), Digital Aqaba City (first digital hub), Smart City with JICA, $88M gas infrastructure. Six new industrial zones planned.",
    sectors: ["Construction", "Infrastructure", "Industrial"],
    deadline: "Ongoing",
    valueMax: "Multi-billion USD",
    status: "open",
  },
  {
    id: "jo-jlgc",
    title: "Jordan Loan Guarantee Corporation (JLGC)",
    type: "financing",
    sourceName: "JLGC",
    sourceCountry: "JO",
    sourceUrl: "https://www.jlgc.com/",
    description: "Loan guarantees for SMEs expanding in Jordan. Construction and contracting companies eligible for project-based guarantees.",
    sectors: ["All Sectors"],
    deadline: "Open",
    valueMax: "Varies",
    status: "open",
  },
  // --- EGYPT ---
  {
    id: "eg-nac",
    title: "Egypt New Administrative Capital — Construction Packages",
    type: "tender",
    sourceName: "ACUD (Administrative Capital for Urban Development)",
    sourceCountry: "EG",
    sourceUrl: "https://www.acud.eg/",
    description: "$58B new administrative capital project. Construction, MEP, and infrastructure packages for government buildings, residential, and commercial zones.",
    sectors: ["Construction", "Infrastructure", "MEP"],
    deadline: "Ongoing phases",
    valueMax: "$58B total project",
    status: "open",
  },
];

// =============================================================================
// MATCHES — SCORED AGAINST AL MOAYYED CONTRACTING GROUP
// =============================================================================

export const matchesAlMoayyed: Match[] = [
  {
    id: "m-acg-1",
    companyId: "almoayyed",
    opportunityId: "bh-tender-board",
    opportunityTitle: "Bahrain Tender Board — Government Procurement",
    opportunityType: "tender",
    sourceName: "Bahrain Tender Board",
    sourceCountry: "BH",
    combinedScore: 97,
    eligibilityScore: 100,
    relevanceScore: 98,
    competitivenessScore: 92,
    recommendation: "strong_match",
    summary: "AA-grade contractor with 54 years of history and landmark Bahrain government project experience. Highest possible qualification for government tenders.",
    keyFactors: [
      "AA Grade — highest Ministry of Works classification",
      "Completed BIA Terminal, F1 Circuit, Ministry of Housing projects",
      "6,500+ employees — full capacity for major government contracts",
      "Established government relationship through decades of projects",
    ],
  },
  {
    id: "m-acg-2",
    companyId: "almoayyed",
    opportunityId: "sa-etimad",
    opportunityTitle: "ETIMAD — Saudi Government eProcurement",
    opportunityType: "tender",
    sourceName: "Saudi Ministry of Finance",
    sourceCountry: "SA",
    combinedScore: 88,
    eligibilityScore: 85,
    relevanceScore: 95,
    competitivenessScore: 82,
    recommendation: "strong_match",
    summary: "Vision 2030 is generating the largest construction pipeline in history. ACG's capabilities in civil, MEP, and FM are directly applicable. Regional registration required.",
    keyFactors: [
      "Construction capabilities directly match Vision 2030 needs",
      "MEP and FM services applicable to mega-projects",
      "GCC-based company can leverage free trade agreements",
      "Would need Saudi contractor registration/partnership",
    ],
  },
  {
    id: "m-acg-3",
    companyId: "almoayyed",
    opportunityId: "sa-rcrc-neom",
    opportunityTitle: "NEOM — The Line & Related Projects",
    opportunityType: "tender",
    sourceName: "NEOM Company / PIF",
    sourceCountry: "SA",
    combinedScore: 85,
    eligibilityScore: 78,
    relevanceScore: 95,
    competitivenessScore: 80,
    recommendation: "strong_match",
    summary: "$500B+ mega-project with massive MEP, civil, and FM subcontracting packages. ACG could partner with Tier-1 contractors for specialized packages.",
    keyFactors: [
      "MEP and civil works capabilities directly applicable",
      "FM division could secure post-construction O&M contracts",
      "AMAS Island JV experience shows capability for mega-project partnerships",
      "Data center construction experience relevant to NEOM tech infrastructure",
    ],
  },
  {
    id: "m-acg-4",
    companyId: "almoayyed",
    opportunityId: "bh-tamkeen-enterprise",
    opportunityTitle: "Tamkeen Enterprise Support Program",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 84,
    eligibilityScore: 90,
    relevanceScore: 82,
    competitivenessScore: 78,
    recommendation: "strong_match",
    summary: "50% cost coverage for software, marketing, and services. ACG could use this for BIM software adoption, ERP upgrades, or digital marketing for the FM/cleaning divisions.",
    keyFactors: [
      "Bahrain-registered with active CR — meets base eligibility",
      "Digital transformation of construction operations eligible",
      "Marketing support for FM/cleaning/security service lines",
      "Software and technology investment support",
    ],
  },
  {
    id: "m-acg-5",
    companyId: "almoayyed",
    opportunityId: "bh-tamkeen-nep",
    opportunityTitle: "National Employment Program 3.0",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 91,
    eligibilityScore: 95,
    relevanceScore: 90,
    competitivenessScore: 88,
    recommendation: "strong_match",
    summary: "As one of Bahrain's largest private employers with 6,500+ staff, ACG is a prime candidate. Wage subsidies directly reduce labor costs across all divisions.",
    keyFactors: [
      "6,500+ employees — massive potential for Bahranization wage subsidies",
      "Multiple divisions (construction, FM, cleaning, security) all eligible",
      "Hospitality/construction among Tamkeen priority sectors",
      "Up to 36 months wage support per hire",
    ],
  },
  {
    id: "m-acg-6",
    companyId: "almoayyed",
    opportunityId: "sa-red-sea",
    opportunityTitle: "The Red Sea Project & AMAALA",
    opportunityType: "tender",
    sourceName: "Red Sea Global / PIF",
    sourceCountry: "SA",
    combinedScore: 83,
    eligibilityScore: 75,
    relevanceScore: 92,
    competitivenessScore: 80,
    recommendation: "strong_match",
    summary: "Luxury hospitality construction and landscaping. ACG's combined construction + landscaping + FM capabilities create a unique full-lifecycle value proposition.",
    keyFactors: [
      "Hotel/resort construction experience from Bahrain projects",
      "Landscaping division relevant to resort developments",
      "FM services create post-construction recurring revenue opportunity",
      "MEP for luxury hospitality is a proven ACG strength",
    ],
  },
  {
    id: "m-acg-7",
    companyId: "almoayyed",
    opportunityId: "og-bapco",
    opportunityTitle: "BAPCO Energies — Procurement",
    opportunityType: "tender",
    sourceName: "BAPCO Energies",
    sourceCountry: "BH",
    combinedScore: 90,
    eligibilityScore: 95,
    relevanceScore: 88,
    competitivenessScore: 85,
    recommendation: "strong_match",
    summary: "Bahrain's national oil company. ACG has local presence, AA-grade status, and construction/FM capabilities suitable for refinery maintenance and facility construction.",
    keyFactors: [
      "Local Bahrain-based — proximity advantage",
      "Industrial construction and MEP capabilities",
      "FM and cleaning services for industrial facilities",
      "ISO 14001 environmental certification",
    ],
  },
  {
    id: "m-acg-8",
    companyId: "almoayyed",
    opportunityId: "og-aramco",
    opportunityTitle: "Saudi Aramco — iSupplier Portal",
    opportunityType: "tender",
    sourceName: "Saudi Aramco",
    sourceCountry: "SA",
    combinedScore: 80,
    eligibilityScore: 72,
    relevanceScore: 90,
    competitivenessScore: 76,
    recommendation: "good_match",
    summary: "World's largest oil company with massive annual construction spend. ACG would need IKTVA qualification but capabilities are directly relevant.",
    keyFactors: [
      "Construction and MEP capabilities match Aramco needs",
      "ISO certifications support pre-qualification",
      "Would need In-Kingdom Total Value Add (IKTVA) registration",
      "JV with Saudi partner would strengthen bid",
    ],
  },
  {
    id: "m-acg-9",
    companyId: "almoayyed",
    opportunityId: "bh-tamkeen-digital",
    opportunityTitle: "Digital Transformation Support",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 82,
    eligibilityScore: 90,
    relevanceScore: 80,
    competitivenessScore: 75,
    recommendation: "good_match",
    summary: "BIM, ERP, IoT, and digital twin adoption for construction. ACG's scale makes digital transformation investment highly impactful and fundable.",
    keyFactors: [
      "BIM implementation across construction projects",
      "Fleet management digitization for transport division",
      "IoT integration for facility management services",
      "Data center construction experience shows tech capability",
    ],
  },
  {
    id: "m-acg-10",
    companyId: "almoayyed",
    opportunityId: "bh-export-finance",
    opportunityTitle: "Export Bahrain Financing",
    opportunityType: "financing",
    sourceName: "Export Bahrain",
    sourceCountry: "BH",
    combinedScore: 78,
    eligibilityScore: 85,
    relevanceScore: 75,
    competitivenessScore: 72,
    recommendation: "good_match",
    summary: "Export financing to support GCC expansion. Subsidized profit rates up to 70% for international market entry — directly applicable to Saudi and UAE project bids.",
    keyFactors: [
      "Bahrain-registered with export potential",
      "GCC expansion for construction services",
      "Export credit insurance for international contracts",
      "BD 1M financing available for overseas business development",
    ],
  },
  {
    id: "m-acg-11",
    companyId: "almoayyed",
    opportunityId: "ml-isdb",
    opportunityTitle: "Islamic Development Bank — Project Finance",
    opportunityType: "financing",
    sourceName: "IsDB",
    sourceCountry: "International",
    combinedScore: 75,
    eligibilityScore: 80,
    relevanceScore: 75,
    competitivenessScore: 68,
    recommendation: "good_match",
    summary: "IsDB-financed infrastructure projects across 57 OIC member countries. ACG can bid on construction packages for IsDB-funded projects in the region.",
    keyFactors: [
      "Bahrain is IsDB member country",
      "Infrastructure and construction are IsDB priority sectors",
      "Regional experience applicable to development bank-funded projects",
      "Sharia-compliant financing aligns with group values",
    ],
  },
  {
    id: "m-acg-12",
    companyId: "almoayyed",
    opportunityId: "ae-etihad-rail",
    opportunityTitle: "Etihad Rail — National Railway",
    opportunityType: "tender",
    sourceName: "Etihad Rail",
    sourceCountry: "AE",
    combinedScore: 76,
    eligibilityScore: 70,
    relevanceScore: 82,
    competitivenessScore: 74,
    recommendation: "good_match",
    summary: "$11B national railway with station buildings, depot construction, and MEP packages. ACG's civil and MEP capabilities are directly applicable.",
    keyFactors: [
      "Station building construction within ACG capabilities",
      "MEP for railway facilities",
      "Could partner with rail-specialist main contractor",
      "FM services for operational stations post-completion",
    ],
  },
  {
    id: "m-acg-13",
    companyId: "almoayyed",
    opportunityId: "eg-nac",
    opportunityTitle: "Egypt New Administrative Capital",
    opportunityType: "tender",
    sourceName: "ACUD",
    sourceCountry: "EG",
    combinedScore: 70,
    eligibilityScore: 65,
    relevanceScore: 80,
    competitivenessScore: 63,
    recommendation: "possible_match",
    summary: "$58B new capital project. Massive construction packages. ACG would need Egypt entity/partnership but capabilities are relevant. Higher competition expected.",
    keyFactors: [
      "Largest urban construction project in the Middle East",
      "Government buildings, residential, and commercial construction",
      "Would need Egyptian JV partner or entity establishment",
      "Higher competition from Egyptian and international contractors",
    ],
  },
  {
    id: "m-acg-14",
    companyId: "almoayyed",
    opportunityId: "sa-roshn",
    opportunityTitle: "ROSHN Housing Developments",
    opportunityType: "tender",
    sourceName: "ROSHN / PIF",
    sourceCountry: "SA",
    combinedScore: 82,
    eligibilityScore: 78,
    relevanceScore: 88,
    competitivenessScore: 78,
    recommendation: "strong_match",
    summary: "PIF-backed residential developer. ACG's AMAS Island housing experience (682 apartments, $166.8M) is directly transferable. FM services for community management.",
    keyFactors: [
      "AMAS Island housing project proves mass residential construction capability",
      "East Sitra housing (546 villas) further validates capability",
      "FM services applicable to community management post-completion",
      "JV approach (as with Airolink on AMAS) could work here",
    ],
  },
  {
    id: "m-acg-16",
    companyId: "almoayyed",
    opportunityId: "bh-metro",
    opportunityTitle: "Bahrain Metro — PPP (Red & Blue Lines)",
    opportunityType: "tender",
    sourceName: "Ministry of Transportation",
    sourceCountry: "BH",
    combinedScore: 93,
    eligibilityScore: 98,
    relevanceScore: 95,
    competitivenessScore: 85,
    recommendation: "strong_match",
    summary: "$2B+ home-market mega-project. ACG's AA-grade, MEP expertise, and local government relationships make it a prime candidate for construction packages or consortium participation.",
    keyFactors: [
      "AA-grade contractor — highest qualification for Bahrain government projects",
      "MEP and civil works core capabilities directly applicable to metro stations",
      "Established relationship with Bahrain Ministry of Works",
      "Could participate in consortium or as MEP subcontractor",
    ],
  },
  {
    id: "m-acg-17",
    companyId: "almoayyed",
    opportunityId: "bh-ewa-substations",
    opportunityTitle: "EWA — New 66kV Substations & Renewable Energy",
    opportunityType: "tender",
    sourceName: "EWA",
    sourceCountry: "BH",
    combinedScore: 91,
    eligibilityScore: 95,
    relevanceScore: 92,
    competitivenessScore: 85,
    recommendation: "strong_match",
    summary: "Home-market electrical infrastructure. ACG's MEP division and Almoayyed Solar capability perfectly positioned for substation construction and renewable installations.",
    keyFactors: [
      "Almoayyed Solar installed Bahrain's first grid-connected PV system",
      "MEP division handles electrical infrastructure projects",
      "Local presence and established EWA relationship",
      "300 MW renewable target creates significant pipeline",
    ],
  },
  {
    id: "m-acg-18",
    companyId: "almoayyed",
    opportunityId: "sa-ksia",
    opportunityTitle: "King Salman International Airport ($30B+)",
    opportunityType: "tender",
    sourceName: "KSIADC",
    sourceCountry: "SA",
    combinedScore: 82,
    eligibilityScore: 75,
    relevanceScore: 92,
    competitivenessScore: 78,
    recommendation: "strong_match",
    summary: "$30B+ airport with massive MEP scope. ACG already has KSA office in Dammam. Subcontracting under Bechtel/Samsung C&T for terminal MEP packages.",
    keyFactors: [
      "Existing KSA presence (Dammam office) reduces entry barrier",
      "BIA Terminal refurbishment ($33.69M) proves airport MEP capability",
      "Subcontracting under Bechtel, Parsons, or Samsung C&T",
      "Terminal HVAC, electrical, plumbing, and fire systems",
    ],
  },
  {
    id: "m-acg-19",
    companyId: "almoayyed",
    opportunityId: "ae-maktoum-airport",
    opportunityTitle: "Al Maktoum Airport Expansion ($35B)",
    opportunityType: "tender",
    sourceName: "DAEP",
    sourceCountry: "AE",
    combinedScore: 79,
    eligibilityScore: 72,
    relevanceScore: 88,
    competitivenessScore: 75,
    recommendation: "good_match",
    summary: "$35B expansion. ACG has Dubai entity (AEMC LLC) already operational. Airport MEP expertise from BIA project. Terminal MEP subcontracting opportunities.",
    keyFactors: [
      "AEMC LLC in Dubai provides existing UAE legal entity",
      "Airport terminal MEP experience from BIA",
      "World's largest airport — enormous MEP scope",
      "Phase 1 completion 2029 creates multi-year pipeline",
    ],
  },
  {
    id: "m-acg-20",
    companyId: "almoayyed",
    opportunityId: "sa-healthcare",
    opportunityTitle: "Saudi Healthcare Mega-Projects ($69.3B)",
    opportunityType: "tender",
    sourceName: "Saudi MOH / PIF",
    sourceCountry: "SA",
    combinedScore: 81,
    eligibilityScore: 73,
    relevanceScore: 90,
    competitivenessScore: 78,
    recommendation: "strong_match",
    summary: "Hospital MEP is among the most specialized and lucrative. 160,000 workers needed at peak 2026. ACG's health center experience (Naim, Arad, Public Security) is directly applicable.",
    keyFactors: [
      "Completed Naim, Arad, and Public Security health centres in Bahrain",
      "Hospital MEP requires specialized HVAC, medical gas, critical power",
      "KSA office in Dammam enables Saudi operations",
      "160,000 construction personnel needed at peak — labor demand high",
    ],
  },
  {
    id: "m-acg-15",
    companyId: "almoayyed",
    opportunityId: "bh-tamkeen-training",
    opportunityTitle: "Professional Training & Certification",
    opportunityType: "training",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 86,
    eligibilityScore: 95,
    relevanceScore: 80,
    competitivenessScore: 82,
    recommendation: "strong_match",
    summary: "With 6,500+ employees, training subsidies for professional certifications (safety, quality, project management) have massive ROI potential across all divisions.",
    keyFactors: [
      "6,500+ employee base creates enormous training subsidy opportunity",
      "Safety certifications (NEBOSH, IOSH) for construction workforce",
      "Project management (PMP, PRINCE2) for management staff",
      "Already achieved 100M hours without LTI — training investment pays off",
    ],
  },
];

// =============================================================================
// MATCHES — SCORED AGAINST NORDIC GROUP (existing)
// =============================================================================

export const matchesNordic: Match[] = [
  {
    id: "m-ng-1",
    companyId: "nordic",
    opportunityId: "bh-bdb-sme",
    opportunityTitle: "BDB SME Fund ($185M)",
    opportunityType: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    combinedScore: 89,
    eligibilityScore: 92,
    relevanceScore: 90,
    competitivenessScore: 85,
    recommendation: "strong_match",
    summary: "Tourism is one of BDB's 7 priority sectors. Fixed asset financing ideal for Nordic Palace renovation (aging property per reviews), Nordic Gardens expansion, or new property acquisition.",
    keyFactors: [
      "Tourism is explicitly listed as BDB priority sector",
      "Nordic Palace needs renovation — financing could fund complete refurbishment",
      "Fixed asset loans for property improvements with 50% Tamkeen rate subsidy",
      "7+ years operational history exceeds 2-year minimum requirement",
    ],
  },
  {
    id: "m-ng-2",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-enterprise",
    opportunityTitle: "Tamkeen Enterprise Support Program",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 85,
    eligibilityScore: 90,
    relevanceScore: 85,
    competitivenessScore: 78,
    recommendation: "strong_match",
    summary: "50% cost coverage for software, marketing, branding. Critical for Nordic's weak social media presence (459 Facebook likes vs thousands for competitors) and hotel tech upgrades.",
    keyFactors: [
      "50% cost coverage for digital marketing — Nordic's weakest area",
      "PMS/booking system upgrades beyond current STAAH setup",
      "Brand development to compete with incoming international chains",
      "Website and mobile app development for direct bookings",
    ],
  },
  {
    id: "m-ng-3",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-nep",
    opportunityTitle: "National Employment Program 3.0",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 83,
    eligibilityScore: 95,
    relevanceScore: 78,
    competitivenessScore: 75,
    recommendation: "strong_match",
    summary: "Wage subsidies for up to 36 months. With 150-250 staff across 3 properties, Nordic can absorb Bahraini hires in housekeeping, front office, F&B, and spa. Accommodation & Food Services is Tamkeen's top sector.",
    keyFactors: [
      "Accommodation & Food Services is #1 Tamkeen-supported sector (~22%)",
      "3 properties provide diverse placement options",
      "Up to 36 months wage support per hire reduces labor costs",
      "Supports Bahranization requirements across all departments",
    ],
  },
  {
    id: "m-ng-4",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-training",
    opportunityTitle: "Professional Training & Certification",
    opportunityType: "training",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 82,
    eligibilityScore: 92,
    relevanceScore: 80,
    competitivenessScore: 72,
    recommendation: "strong_match",
    summary: "Staff certifications in food safety (HACCP), hotel management, spa therapy, revenue management. Nordic has no certifications currently — this addresses a gap that reduces match scores.",
    keyFactors: [
      "No certifications detected — training fills a critical gap",
      "HACCP food safety certification for F&B operations",
      "Spa therapy certifications for wellness staff",
      "Revenue management training for OTA optimization",
    ],
  },
  {
    id: "m-ng-5",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-digital",
    opportunityTitle: "Digital Transformation Support",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 81,
    eligibilityScore: 88,
    relevanceScore: 78,
    competitivenessScore: 75,
    recommendation: "strong_match",
    summary: "Fund full-stack hospitality tech: PMS upgrade, revenue management, guest experience app, self-check-in kiosks. Nordic uses STAAH but could upgrade to Opera/Mews + RMS.",
    keyFactors: [
      "Already on STAAH — demonstrates tech adoption readiness",
      "PMS upgrade (STAAH → Opera Cloud or Mews) for better analytics",
      "Guest-facing mobile app for check-in/services/dining",
      "CRM and marketing automation for direct booking growth",
    ],
  },
  {
    id: "m-ng-6",
    companyId: "nordic",
    opportunityId: "bh-tamkeen-export",
    opportunityTitle: "Export / Overseas Expansion Program",
    opportunityType: "grant",
    sourceName: "Tamkeen",
    sourceCountry: "BH",
    combinedScore: 72,
    eligibilityScore: 78,
    relevanceScore: 65,
    competitivenessScore: 72,
    recommendation: "good_match",
    summary: "Could fund GCC marketing campaigns targeting Saudi Arabia (58% of Bahrain visitors), exhibition attendance at ATM Dubai/AHIC, or management contract pursuit in KSA/Oman.",
    keyFactors: [
      "Saudi Arabia is 58% of Bahrain's visitor market",
      "Support for trade exhibitions (ATM Dubai, AHIC, WTM London)",
      "Overseas management contract business development",
      "Marketing campaigns in Saudi/GCC source markets",
    ],
  },
  {
    id: "m-ng-7",
    companyId: "nordic",
    opportunityId: "bh-export-finance",
    opportunityTitle: "Export Bahrain Financing",
    opportunityType: "financing",
    sourceName: "Export Bahrain",
    sourceCountry: "BH",
    combinedScore: 68,
    eligibilityScore: 75,
    relevanceScore: 62,
    competitivenessScore: 65,
    recommendation: "good_match",
    summary: "Export financing for international market expansion. Could support Saudi/Oman hotel management contract pursuit, international trade show participation, or franchise export.",
    keyFactors: [
      "BD 1M financing with 70% profit rate subsidy",
      "Export credit insurance for international management contracts",
      "Saudi Vision 2030 targets 150M tourists — management contract opportunity",
      "Oman tourism development needs experienced operators",
    ],
  },
  {
    id: "m-ng-8",
    companyId: "nordic",
    opportunityId: "bh-edb-investment",
    opportunityTitle: "EDB Investment Facilitation",
    opportunityType: "incentive",
    sourceName: "Bahrain EDB",
    sourceCountry: "BH",
    combinedScore: 76,
    eligibilityScore: 85,
    relevanceScore: 72,
    competitivenessScore: 70,
    recommendation: "good_match",
    summary: "Free facilitation for hotel investment. Tourism is EDB priority sector. Support for new property acquisition, expansion planning, and incentive packages.",
    keyFactors: [
      "Tourism explicitly listed as EDB priority sector",
      "0% corporate tax in Bahrain — already benefiting",
      "Facilitation for new hotel development or acquisition",
      "Incentive packages for hospitality investment",
    ],
  },
  {
    id: "m-ng-9",
    companyId: "nordic",
    opportunityId: "bh-bdb-finance",
    opportunityTitle: "BDB & Tamkeen Joint Finance",
    opportunityType: "financing",
    sourceName: "Bahrain Development Bank",
    sourceCountry: "BH",
    combinedScore: 80,
    eligibilityScore: 85,
    relevanceScore: 78,
    competitivenessScore: 75,
    recommendation: "good_match",
    summary: "Subsidized working capital and business loans. Nordic could use for seasonal cash flow management, renovation financing, or new property down-payment.",
    keyFactors: [
      "Subsidized profit rates reduce cost of capital",
      "Working capital for seasonal cash flow peaks/troughs",
      "Hotel renovation financing (Nordic Palace needs refurbishment)",
      "Growth capital for 4th property acquisition",
    ],
  },
  {
    id: "m-ng-10",
    companyId: "nordic",
    opportunityId: "bh-bdb-invoice",
    opportunityTitle: "BDB Invoice Discounting (Tijara)",
    opportunityType: "financing",
    sourceName: "BDB / Tijara",
    sourceCountry: "BH",
    combinedScore: 65,
    eligibilityScore: 72,
    relevanceScore: 60,
    competitivenessScore: 62,
    recommendation: "good_match",
    summary: "Early payment on corporate invoices. Useful for MICE/events division where corporate clients have 30-60 day payment terms.",
    keyFactors: [
      "Corporate event bookings often have delayed payment",
      "Improves cash flow from B2B MICE business",
      "Digital platform for easy access",
      "Partnership with major buyers — could include hotel corporate accounts",
    ],
  },
  {
    id: "m-ng-11",
    companyId: "nordic",
    opportunityId: "ae-khalifa-fund",
    opportunityTitle: "Khalifa Fund for Enterprise Development",
    opportunityType: "financing",
    sourceName: "Khalifa Fund",
    sourceCountry: "AE",
    combinedScore: 58,
    eligibilityScore: 50,
    relevanceScore: 65,
    competitivenessScore: 58,
    recommendation: "possible_match",
    summary: "If Nordic expands to Abu Dhabi, Khalifa Fund provides SME financing and advisory. UAE hospitality market is booming. Requires UAE entity establishment.",
    keyFactors: [
      "UAE hospitality market — 100 hotel projects, 25,470 rooms in pipeline",
      "Advisory services for market entry",
      "Would require UAE entity/license",
      "Longer-term expansion opportunity",
    ],
  },
  {
    id: "m-ng-12",
    companyId: "nordic",
    opportunityId: "om-riyada",
    opportunityTitle: "Riyada (Oman SME Development) / Al Raffd Fund",
    opportunityType: "financing",
    sourceName: "Riyada",
    sourceCountry: "OM",
    combinedScore: 55,
    eligibilityScore: 45,
    relevanceScore: 68,
    competitivenessScore: 52,
    recommendation: "possible_match",
    summary: "Oman has 27 hotel projects (4,709 rooms) in pipeline. If Nordic pursues management contracts in Oman, Riyada/Al Raffd provides SME support.",
    keyFactors: [
      "27 hotel projects in Oman pipeline — management contract opportunity",
      "Oman tourism strategy targeting diversification from oil",
      "Musandam/Duqm/Salalah resort developments need operators",
      "Requires Oman entity — longer-term strategic play",
    ],
  },
  {
    id: "m-ng-13",
    companyId: "nordic",
    opportunityId: "sa-monshaat",
    opportunityTitle: "Monsha'at SME Support (Saudi Arabia)",
    opportunityType: "grant",
    sourceName: "Monsha'at",
    sourceCountry: "SA",
    combinedScore: 62,
    eligibilityScore: 55,
    relevanceScore: 72,
    competitivenessScore: 58,
    recommendation: "possible_match",
    summary: "Saudi Vision 2030 targets 150M tourists. Monsha'at supports hospitality SMEs entering Saudi market. Nordic's halal/family-focused brand aligns perfectly with Saudi values.",
    keyFactors: [
      "Saudi Vision 2030 — 150M tourist target creates operator demand",
      "Nordic's halal/dry hotel concept perfectly aligned with Saudi market",
      "Family-focused brand matches Saudi tourism development strategy",
      "Advisory and financing support for market entry",
    ],
  },
  {
    id: "m-ng-14",
    companyId: "nordic",
    opportunityId: "ml-isdb",
    opportunityTitle: "Islamic Development Bank — Tourism Finance",
    opportunityType: "financing",
    sourceName: "IsDB",
    sourceCountry: "International",
    combinedScore: 60,
    eligibilityScore: 65,
    relevanceScore: 58,
    competitivenessScore: 55,
    recommendation: "possible_match",
    summary: "IsDB supports tourism infrastructure in OIC member countries. Nordic's halal hospitality model could attract IsDB support for expansion into other Muslim-majority markets.",
    keyFactors: [
      "Bahrain is IsDB member — eligible for programs",
      "Halal tourism is IsDB strategic priority",
      "Technical assistance for hospitality development",
      "Cross-border expansion financing possibility",
    ],
  },
];

// Helper to get all matches for a company
export function getMatchesForCompany(companyId: string): Match[] {
  if (companyId === "almoayyed") return matchesAlMoayyed;
  if (companyId === "nordic") return matchesNordic;
  return [];
}

// Helper to get all opportunities relevant to a company's matches
export function getOpportunitiesForCompany(companyId: string): Opportunity[] {
  const matches = getMatchesForCompany(companyId);
  const oppIds = new Set(matches.map((m) => m.opportunityId));
  return opportunities.filter((o) => oppIds.has(o.id));
}
